### ISSUE TITLE
"createOrAddLabel" failing

### ISSUE THREAD

**Issue by sogame** [danger/danger-js#1008]
Hi,

I just started trying to create a label from my dangerfile, but it seems to be failing.

I'm using `danger@9.2.10`, and when running:
```
danger.github.utils.createOrAddLabel({ name: 'My Label', color: '00ff00', description: 'Label desc' });
```
I'm getting this error in Travis logs:
```
Error:  { HttpError: Not Found
    at response.text.then.message (/home/travis/build/sogame/danger-plugin-toolbox/node_modules/@octokit/request/dist-node/index.js:66:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HttpError',
  status: 404,
  headers:
   { 'access-control-allow-origin': '*',
     'access-control-expose-headers':
      'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
     connection: 'close',
     'content-encoding': 'gzip',
     'content-security-policy': 'default-src \'none\'',
     'content-type': 'application/json; charset=utf-8',
     date: 'Wed, 04 Mar 2020 20:14:32 GMT',
     'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
     server: 'GitHub.com',
     status: '404 Not Found',
     'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
     'transfer-encoding': 'chunked',
     vary: 'Accept-Encoding, Accept, X-Requested-With',
     'x-accepted-oauth-scopes': '',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'deny',
     'x-github-media-type': 'github.v3; format=json',
     'x-github-request-id': 'C724:1C90:119FE2:218AB5:5E600C27',
     'x-oauth-scopes': 'public_repo',
     'x-ratelimit-limit': '5000',
     'x-ratelimit-remaining': '4794',
     'x-ratelimit-reset': '1583354192',
     'x-xss-protection': '1; mode=block' },
  request:
   { method: 'POST',
     url:
      'https://api.github.com/repos/sogame/danger-plugin-toolbox/labels',
     headers:
      { accept: 'application/vnd.github.v3+json',
        'user-agent': 'octokit.js/16.37.0 Node.js/10.13.0 (Linux 4.15; x64)',
        authorization: 'token [REDACTED]',
        'content-type': 'application/json; charset=utf-8' },
     body:
      '{"name":"FirstLabel","color":"00ff00","description":"Label desc"}',
     request:
      { hook: [Function: bound bound register], validate: [Object] } },
  documentation_url:
   'https://developer.github.com/v3/issues/labels/#create-a-label' }
```

Am I doing something wrong? Or is this functionality currently broken?

Thanks a lot!

**Comment by orta** [comment]
Does your token have access rights to make a new label?

**Comment by sogame** [comment]
🤦‍♂ sorry about this, you're totally right @orta, it was missing write access 😞 

To make up for it, I've created this tiny PR: https://github.com/danger/danger-js/pull/1011

**Comment by orta** [comment]
No worries, this well structured issue should be easy to find for the next person who hits that
