### ISSUE TITLE
Using custom github app doesn't work well

### ISSUE THREAD

**Issue by pinkasey** [danger/danger-js#1054]
**Describe the bug**
I'm trying to integrate Danger with my CI (Jenkins), via a custom Github App.

I've tried passing
- `DANGER_GITHUB_APP_PRIVATE_SIGNING_KEY`
- `DANGER_GITHUB_APP_ID`
- `DANGER_GITHUB_APP_INSTALL_ID` 
(found it by accident in `CHANGELOG.md`), 
but then Danger says:
```
10:26:59  The DANGER_GITHUB_API_TOKEN/DANGER_BITBUCKETSERVER_HOST/DANGER_GITLAB_API_TOKEN environmental variable is missing
10:26:59  Without an api token, danger will be unable to comment on a PR
10:26:59  Error:  Error: Cannot use authenticated API requests.
10:26:59      at Object.getPlatformForEnv (.../node_modules/danger/distribution/platforms/platform.js:76:11)
10:26:59      at Object.<anonymous> (.../node_modules/danger/distribution/commands/ci/runner.js:81:57)
10:26:59      at step (.../node_modules/danger/distribution/commands/ci/runner.js:32:23)
10:26:59      at Object.next (.../node_modules/danger/distribution/commands/ci/runner.js:13:53)
10:26:59      at fulfilled (.../node_modules/danger/distribution/commands/ci/runner.js:4:58)
```

So I've tried another approach -
I'm using the relatively-new integration of [Jenkins with GitHub](https://www.jenkins.io/blog/2020/04/16/github-app-authentication/), to get the Github-App's access token, and I pass that to Danger.
That actually works.
With one caveat -
Danger is unable to detect its own comments, so he can't update existing comment. Instead it adds new one every time it runs.
I'm getting two warnings in the Jenkins log, I'm not sure what the second one means (they repeat themselves several times):
```
10:39:09  Failing the build, there are 2 fails.
10:39:09  Request failed [403]: https://api.github.com/user
10:39:09  Response: {
10:39:09    "message": "Resource not accessible by integration",
10:39:09    "documentation_url": "https://developer.github.com/v3/users/#get-the-authenticated-user"
10:39:09  }
10:39:10  Request failed [422]: https://api.github.com/repos/next-insurance/skyscraper/pulls/17224/comments
10:39:10  Response: {
10:39:10    "message": "Validation Failed",
10:39:10    "errors": [
10:39:10      {
10:39:10        "resource": "PullRequestReviewComment",
10:39:10        "code": "custom",
10:39:10        "field": "pull_request_review_id",
10:39:10        "message": "pull_request_review_id must be pending"
10:39:10      }
10:39:10    ],
10:39:10    "documentation_url": "https://developer.github.com/v3/pulls/comments/#create-a-comment"
10:39:10  }
```

**To Reproduce**
1. Setup Jenkins pipeline integration with Danger, with a custom Github app*
\* It's not a simple task. Took me 4 days. I might be able to open-source it.
2. Provide credentials via DANGER_GITHUB_APP_PRIVATE_SIGNING_KEY and friends
3. Danger fails

**Expected behavior**

**Screenshots**

** Your Environment**

 | software         | version
| -------------- | -------
| danger.js         | 10.2.1
| node                | not sure, I think latest (I use https://github.com/timbru31/docker-java-node/blob/master/8/jdk/alpine/Dockerfile)
| npm                 | not sure, I think latest (I use https://github.com/timbru31/docker-java-node/blob/master/8/jdk/alpine/Dockerfile)
| Operating System | linux

**Additional context**

**Comment by koji-1009** [comment]
Hi, I am facing the same problem.
For this reason, I created a project for reproduction.

<https://github.com/koji-1009/pending_pull_request_review_id/pull/1/checks>

**Comment by koji-1009** [comment]
I'm beginner of Ruby and JS (TS).
So I can't say for sure, but I'm finding the difference between the two implementations.

In Danger-Ruby, inline comments are merged and send. 
Perhaps there will be one or a minimum number of API requests per file.
- <https://github.com/danger/danger/blob/v8.0.5/lib/danger/request_sources/github/github.rb#L259>
- <https://github.com/danger/danger/blob/v8.0.5/lib/danger/helpers/comments_helper.rb#L94>
- <https://github.com/danger/danger/blob/v8.0.5/lib/danger/request_sources/vsts_api.rb#L80>

In Danger-JS, inline comments are send by `promise`.
Perhaps there will be multiple API requests per file.
- <https://github.com/danger/danger-js/blob/10.4.0/source/runner/Executor.ts#L395>
- <https://github.com/danger/danger-js/blob/10.4.0/source/platforms/github/comms/issueCommenter.ts#L84>
- <https://github.com/danger/danger-js/blob/10.4.0/source/platforms/github/GitHubAPI.ts#L159>

I suspect that the difference between the two is related to the API errors.

**Comment by elanoism** [comment]
@pinkasey , we are seeing the exact same issue (multiple comments) when using a github app. Wonder did you came up with a workaround?

**Comment by pinkasey** [comment]
> [@pinkasey](https://github.com/pinkasey) , we are seeing the exact same issue (multiple comments) when using a github app. Wonder did you came up with a workaround?

Sorry
It was 4+ years ago, I don't remember how I overcame it...
I remember that eventually we used the more sophisticated version of Jenkins, with yamls that define your jobs, and master-slave setup... something complicated and robust.

In my current organization, I plan to implement danger as well, and when I do - I'd use github actions. The easy way.
The reason I used Jenkins back then had to do with security requirements of my org. Unreasonable requirements, IMO.
