### ISSUE TITLE
[BUG] fs not defined when not using babel

### ISSUE THREAD

**Issue by k0nserv** [danger/danger-js#1081]
**Describe the bug**
When not using babel or typescript `fs` is not available via `require`.

**To Reproduce**
1. `npm i -d danger`
2. `danger init`
3.  Use the below `dangerfile.js`

```js
const fs = require('fs');
const { message } = require('danger');

fs.promises.stat('myfile').then(stat => message('hello'));
```

**Expected behavior**

Danger should run without issue and post the message.

**Actual behavior**
Danger errors with the error `fs is not defined` on line 4.

** Your Environment**

 | software         | version
| ---------------- | -------
| danger.js          | 10.5.0
| node             | 12.18.4
| npm              | 6.14.2
| Operating System | macOS 10.15

**Additional context**

**Comment by k0nserv** [comment]
Here's an example [commit](https://github.com/Skyscanner/backpack-ios/commit/09dbecb699a6540ceb19d0fdc966bbbdd8425358) and [failure message](https://github.com/Skyscanner/backpack-ios/pull/786#issuecomment-716682858) that might dissappear in the future

**Comment by orta** [comment]
This is likely babel transpiling into something weird (it's basically impossible to not have a dep tree without babel in it, so it'll be picked up) - if you run with `DEBUG = *` danger should show you what it's running - otherwise try  setting `DANGER_DISABLE_TRANSPILATION=true` to disable it completely.

**Comment by k0nserv** [comment]
Good shout re babel being in the tree turns out we do have it. However from the `DEBUG=*` output(see below) danger is not using it. `DANGER_DISABLE_TRANSPILATION=true` fails with the same error(at least with `danger local`, will try with `danger ci` next)

```
  danger:localGetDiff > git diff master...HEAD +0ms
  danger:process_runner Debug mode on for Danger v10.5.0 +0ms
  danger:process_runner Starting sub-process run +0ms
  danger:localGetDiff > git log master...HEAD --pretty=format:{ "sha": "%H", "parents": "%p", "author": {"name": "%an", "email": "%ae", "date": "%ai" }, "committer": {"name": "%cn", "email": "%ce", "date": "%ci" }, "message": "%f"}, +0ms
  danger:process_runner {
  danger:process_runner   dangerJSONDSL: {
  danger:process_runner     git: {
  danger:process_runner       fileMatch: [Function],
  danger:process_runner       modified_files: [Array],
  danger:process_runner       created_files: [Array],
  danger:process_runner       deleted_files: [Array],
  danger:process_runner       commits: [],
  danger:process_runner       diffForFile: [Function: diffForFile],
  danger:process_runner       structuredDiffForFile: [Function: structuredDiffForFile],
  danger:process_runner       JSONPatchForFile: [Function: JSONPatchForFile],
  danger:process_runner       JSONDiffForFile: [Function: JSONDiffForFile],
  danger:process_runner       linesOfCode: [Function: linesOfCode]
  danger:process_runner     },
  danger:process_runner     local_git: null,
  danger:process_runner     settings: { github: [Object], cliArgs: [Object] }
  danger:process_runner   }
  danger:process_runner } +21ms
  danger:process_runner Preparing to run: /Users/hugotunius/.nvm/versions/node/v12.16.1/bin/node,/Users/hugotunius/Code/Personal/backpack-ios/node_modules/danger/distribution/commands/danger-runner.js +2ms
  danger:runDangerSubprocess Running sub-process: node - /Users/hugotunius/Code/Personal/backpack-ios/node_modules/danger/distribution/commands/danger-runner.js +0ms
  danger:runDangerSubprocess Started passing in STDIN +4ms
  danger:runDangerSubprocess Passed DSL in via STDIN +1ms
2020-10-27T12:53:44.969Z danger:runner Started Danger runner with

2020-10-27T12:53:44.975Z danger:runner Got STDIN for Danger Run

2020-10-27T12:53:44.976Z danger:jsonToDSL Creating pr DSL from JSON

2020-10-27T12:53:44.994Z danger:localGetDiff > git diff master...HEAD

2020-10-27T12:53:45.019Z danger:localGetDiff > git log master...HEAD --pretty=format:{ "sha": "%H", "parents": "%p", "author": {"name": "%an", "email": "%ae", "date": "%ai" }, "committer": {"name": "%cn", "email": "%ce", "date": "%ci" }, "message": "%f"},

2020-10-27T12:53:45.036Z danger:runner Evaluating dangerfile.js

2020-10-27T12:53:45.038Z danger:transpiler:setup Does not have TypeScript set up

2020-10-27T12:53:45.039Z danger:transpiler:setup Does not have Babel set up

2020-10-27T12:53:45.039Z danger:inline_runner Started parsing Dangerfile:  dangerfile.js

2020-10-27T12:53:45.040Z danger:inline_runner Finished running dangerfile:  dangerfile.js

2020-10-27T12:53:45.040Z danger:inline_runner Scheduler waiting on: 1 tasks

Unable to evaluate the Dangerfile
 ReferenceError: fs is not defined
    at hasNonRTLAnchor (dangerfile.js:31:16)
    at Array.map (<anonymous>)
    at dangerfile.js:47:33
    at /Users/hugotunius/Code/Personal/backpack-ios/node_modules/danger/distribution/runner/runners/inline.js:84:32
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/hugotunius/Code/Personal/backpack-ios/node_modules/danger/distribution/runner/runners/inline.js:76:68)
    at step (/Users/hugotunius/Code/Personal/backpack-ios/node_modules/danger/distribution/runner/runners/inline.js:32:23)
    at Object.next (/Users/hugotunius/Code/Personal/backpack-ios/node_modules/danger/distribution/runner/runners/inline.js:13:53)
    at /Users/hugotunius/Code/Personal/backpack-ios/node_modules/danger/distribution/runner/runners/inline.js:7:71
    at new Promise (<anonymous>)

2020-10-27T12:53:45.043Z danger:inline_runner Got a parse error:  ReferenceError: fs is not defined
    at hasNonRTLAnchor (dangerfile.js:31:16)
    at Array.map (<anonymous>)
    at dangerfile.js:47:33
    at /Users/hugotunius/Code/Personal/backpack-ios/node_modules/danger/distribution/runner/runners/inline.js:84:32
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/hugotunius/Code/Personal/backpack-ios/node_modules/danger/distribution/runner/runners/inline.js:76:68)
    at step (/Users/hugotunius/Code/Personal/backpack-ios/node_modules/danger/distribution/runner/runners/inline.js:32:23)
    at Object.next (/Users/hugotunius/Code/Personal/backpack-ios/node_modules/danger/distribution/runner/runners/inline.js:13:53)
    at /Users/hugotunius/Code/Personal/backpack-ios/node_modules/danger/distribution/runner/runners/inline.js:7:71
    at new Promise (<anonymous>)
```

**Comment by curtvict** [comment]
I can confirm that this is happening to me as well

- node v16.13.1
- danger v10.8.0
- ubuntu v21.04

Using Create React App v4.0.3, which has Babel & Webpack enabled by default

**Comment by vlod** [comment]
My workaround was to convert it to typescript and do ```import * as fs from 'fs';```

**Comment by curtvict** [comment]
Thanks @vlod
