### ISSUE TITLE
[BUG] Sporadic error on Codeship CI

### ISSUE THREAD

**Issue by nadavkaner** [danger/danger-js#1100]
**Describe the bug**
I'm using Codeship in order to run danger command in the CI, and from time to time the `danger ci` command failed with the following error:
```
> danger ci

Timeout: Failed to get the Danger DSL after 1 second

TypeError: Cannot read property 'markdowns' of undefined
    at /srv/app/node_modules/danger/distribution/commands/danger-runner.js:119:27
    at /srv/app/node_modules/node-cleanup/node-cleanup.js:80:9
    at Array.forEach (<anonymous>)
    at process.exitHandler (/srv/app/node_modules/node-cleanup/node-cleanup.js:79:21)
    at process.emit (events.js:198:13)
    at process.exit (internal/process/per_thread.js:168:15)
    at Timeout._onTimeout (/srv/app/node_modules/danger/distribution/commands/danger-runner.js:132:17)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)

Failing the build, there is 1 fail.
```

**To Reproduce**
I don't know how to reproduce since it happens sporadically 

 | software         | version
| ---------------- | -------
| danger.js          |  10.4.0
| node             | 10.19.0
| npm              | 6.4.1

**Comment by orta** [comment]
No idea I'm afraid, never used codeship

**Comment by sotomaque** [comment]
any updates on this

**Comment by orta** [comment]
Nope, you're welcome to start 👍🏻
