### ISSUE TITLE
[BUG] Error:  TypeError: commits.map is not a function

### ISSUE THREAD

**Issue by agriardyan** [danger/danger-js#1133]
**Describe the bug**
My code is in self-hosted GitLab repo. I've been stuck integrating the dangerjs with GitLab pipeline in my project for some times now. The error is always the same. Look for the snippet below.

The error occured even before anything run. I've tried to add `message('something ...')` right after `import {danger,message} from danger` yet the error persist.

I've added DANGER_GITLAB_API_TOKEN (with api permission), DANGER_GITLAB_HOST and DANGER_GITLAB_API_BASE_URL. We didn't use any firewall so both https and git url should work no problem.
```
Error: TypeError: commits.map is not a function

[17912](https://gitlab.cloud.mycompany.io/mycompany/my-project/-/jobs/8476922#L17912) at GitLab.<anonymous> (/builds/mycompany/my-project/node_modules/danger/distribution/platforms/GitLab.js:97:49)

[17913](https://gitlab.cloud.mycompany.io/mycompany/my-project/-/jobs/8476922#L17913) at step (/builds/mycompany/my-project/node_modules/danger/distribution/platforms/GitLab.js:44:23)

[17914](https://gitlab.cloud.mycompany.io/mycompany/my-project/-/jobs/8476922#L17914) at Object.next (/builds/mycompany/my-project/node_modules/danger/distribution/platforms/GitLab.js:25:53)

[17915](https://gitlab.cloud.mycompany.io/mycompany/my-project/-/jobs/8476922#L17915) at fulfilled (/builds/mycompany/my-project/node_modules/danger/distribution/platforms/GitLab.js:16:58)

[17916](https://gitlab.cloud.mycompany.io/mycompany/my-project/-/jobs/8476922#L17916) at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**To Reproduce**
1. Add dangerfile.js and npm i danger --save-dev
2. Integrate to GitLab pipeline, run with `yarn danger ci` or `npx danger ci`

**Expected behavior**
script successfully executed

**Your Environment**

 | software         | version
| ---------------- | -------
| danger.js          | 10.6.4
| node             | node:12-alpine3.11
| npm              | 
| Operating System | alpine

**Comment by orta** [comment]
Perhaps the  API for commits isn't giving back the data we expect, I'd recommend running with `DEBUG=*` and looking at the API calls / responses.

**Comment by agriardyan** [comment]
It seems that getMergeRequestCommits resulting in html document, which seemingly a signin page of GitLab. My access token permissions are api, read-api and read-repository. I'm sure Danger won't need write-repository, no?

**Comment by orta** [comment]
No idea, I've never used GitLab - does sound like an access or API call issue

**Comment by agriardyan** [comment]
Turned out mistake from my end. I was misconfigure the host address. Thanks for prompt reply, going to close this issue.

Btw, it seems that the code related to API calls could be improved by adding exception handling. I can create PR if you're okay with that.

**Comment by orta** [comment]
Sure 👍🏻
