### ISSUE TITLE
Error: Unable to evaluate the Dangerfile when running locally / GH Actions

### ISSUE THREAD

**Issue by siggerzz** [danger/danger-js#1310]
**Describe the bug**
During a migration to GitHub Actions on the repo I'm currently working in, I've noticed an issue where I get the following error:

```
2022-09-13T09:35:06.5575334Z $ /home/runner/work/fozzie-components/fozzie-components/node_modules/.bin/danger ci --failOnErrors
2022-09-13T09:35:08.0993364Z Unable to evaluate the Dangerfile
2022-09-13T09:35:08.0994159Z  TypeError: Cannot read properties of  (reading 'body')
2022-09-13T09:35:08.0994629Z     at Object.<anonymous> (dangerfile.js:18:24)
2022-09-13T09:35:08.0995083Z     at Module._compile (node:internal/modules/cjs/loader:1126:14)
2022-09-13T09:35:08.0996063Z     at requireFromString (/home/runner/work/fozzie-components/fozzie-components/node_modules/require-from-string/index.js:28:4)
2022-09-13T09:35:08.0996982Z     at /home/runner/work/fozzie-components/fozzie-components/node_modules/danger/distribution/runner/runners/inline.js:157:68
2022-09-13T09:35:08.0997808Z     at step (/home/runner/work/fozzie-components/fozzie-components/node_modules/danger/distribution/runner/runners/inline.js:52:23)
2022-09-13T09:35:08.0998715Z     at Object.next (/home/runner/work/fozzie-components/fozzie-components/node_modules/danger/distribution/runner/runners/inline.js:33:53)
2022-09-13T09:35:08.0999548Z     at /home/runner/work/fozzie-components/fozzie-components/node_modules/danger/distribution/runner/runners/inline.js:27:71
2022-09-13T09:35:08.1000027Z     at new Promise (<anonymous>)
2022-09-13T09:35:08.1001062Z     at __awaiter (/home/runner/work/fozzie-components/fozzie-components/node_modules/danger/distribution/runner/runners/inline.js:23:12)
2022-09-13T09:35:08.1002004Z     at runDangerfileEnvironment (/home/runner/work/fozzie-components/fozzie-components/node_modules/danger/distribution/runner/runners/inline.js:118:132)
2022-09-13T09:35:08.1002370Z 
2022-09-13T09:35:17.1151153Z 
2022-09-13T09:35:17.1372079Z Danger: ⅹ Failing the build, there is 1 fail.
2022-09-13T09:35:17.1374265Z ## Failures
2022-09-13T09:35:17.1376738Z Danger failed to run `dangerfile.js`.
2022-09-13T09:35:17.1380175Z ## Markdowns
2022-09-13T09:35:17.1382912Z ## Error TypeError
2022-09-13T09:35:17.1383346Z ```
2022-09-13T09:35:17.1384167Z Cannot read properties of undefined (reading 'body')
2022-09-13T09:35:17.1385710Z TypeError: Cannot read properties of undefined (reading 'body')
2022-09-13T09:35:17.1386266Z     at Object.<anonymous> (dangerfile.js:18:24)
2022-09-13T09:35:17.1386828Z     at Module._compile (node:internal/modules/cjs/loader:1126:14)
2022-09-13T09:35:17.1387950Z     at requireFromString (/home/runner/work/fozzie-components/fozzie-components/node_modules/require-from-string/index.js:28:4)
2022-09-13T09:35:17.1388977Z     at /home/runner/work/fozzie-components/fozzie-components/node_modules/danger/distribution/runner/runners/inline.js:157:68
2022-09-13T09:35:17.1390000Z     at step (/home/runner/work/fozzie-components/fozzie-components/node_modules/danger/distribution/runner/runners/inline.js:52:23)
2022-09-13T09:35:17.1391042Z     at Object.next (/home/runner/work/fozzie-components/fozzie-components/node_modules/danger/distribution/runner/runners/inline.js:33:53)
2022-09-13T09:35:17.1392171Z     at /home/runner/work/fozzie-components/fozzie-components/node_modules/danger/distribution/runner/runners/inline.js:27:71
2022-09-13T09:35:17.1392713Z     at new Promise (<anonymous>)
2022-09-13T09:35:17.1393521Z     at __awaiter (/home/runner/work/fozzie-components/fozzie-components/node_modules/danger/distribution/runner/runners/inline.js:23:12)
2022-09-13T09:35:17.1394592Z     at runDangerfileEnvironment (/home/runner/work/fozzie-components/fozzie-components/node_modules/danger/distribution/runner/runners/inline.js:118:132)
2022-09-13T09:35:17.1395184Z ```
2022-09-13T09:35:17.1395913Z ### Dangerfile
2022-09-13T09:35:17.1396256Z ```
2022-09-13T09:35:17.1396796Z 13|         'packages/components/molecules/',
2022-09-13T09:35:17.1397404Z 14|         'packages/components/organisms/',
2022-09-13T09:35:17.1397986Z 15|         'packages/components/templates/',
2022-09-13T09:35:17.1398527Z 16|         'packages/components/pages/',
2022-09-13T09:35:17.1399199Z 17|         'packages/services/',
2022-09-13T09:35:17.1399680Z --------------------------^
2022-09-13T09:35:17.1400157Z 18|         'packages/tools/',
2022-09-13T09:35:17.1400640Z 19|         'packages/storybook'
2022-09-13T09:35:17.1401079Z 20|     ];
2022-09-13T09:35:17.1401575Z 21|     const modifiedFiles = danger.git.modified_files;
2022-09-13T09:35:17.1401970Z ```
2022-09-13T09:35:17.1402262Z   
2022-09-13T09:35:17.1406955Z 
2022-09-13T09:35:17.1618563Z error Command failed with exit code 1.

```

**Expected behavior**
Danger checks work as expected (this config runs fine against our existing CircleCI infrastructure)

 | software         | version
| ---------------- | -------
| danger.js          | 11.1.2
| node             | 16.14.2
| npm              | 8.5.0
| Operating System | MacOS (local) / Ubuntu runner (GH Actions)

**Additional context**
[danger file can be seen here](https://github.com/justeat/fozzie-components/blob/master/dangerfile.js)
[GH Actions migration PR can be seen here](https://github.com/justeat/fozzie-components/pull/2121)

**Comment by orta** [comment]
This crash is coming from your user-land code, I'd recommend digging into why accessing 'body' somewhere is crashing.

**Comment by siggerzz** [comment]
@orta All sorted!


I had to modify the following in my Github Actions config from:

```
on:
  push:
    branches:
    - master
```

to:
```
on:
  pull_request
```

I didn't realise that Danger didn't have access to the `github` object unless the `pull_request` event is used!
