### ISSUE TITLE
CodeShip is not working correctly

### ISSUE THREAD

**Issue by deecewan** [danger/danger-js#150]
Mostly leaving this here as a reminder for me to fix it when I get home:

```
yarn danger v0.20.3
$ danger 
OK, looks good Codeship on GitHub
Error:  TypeError: Cannot convert  or null to object
at Function.from (native)
at _toConsumableArray (dangerfile.js:1:303)
at Object.<anonymous> (dangerfile.js:10:101)
at Runtime._execModule (~/node_modules/jest-runtime/build/index.js:442:13)
at Runtime.requireModule (~/node_modules/jest-runtime/build/index.js:296:14)
at ~/node_modules/danger/distribution/runner/DangerfileRunner.js:110:25
at ensureCleanDangerfile (~/node_modules/danger/distribution/runner/DangerfileRunner.js:131:5)
at Object.<anonymous> (~/node_modules/danger/distribution/runner/DangerfileRunner.js:109:13)
at step (~/node_modules/danger/distribution/runner/DangerfileRunner.js:32:23)
at Object.next (~/node_modules/danger/distribution/runner/DangerfileRunner.js:13:53)
error Command failed with exit code 1.
not running danger
```

**Comment by deecewan** [comment]
Turns out I was just using the incorrect variable names - ignore this.
