### ISSUE TITLE
Github enterprise, 404 when trying to get PR reviews

### ISSUE THREAD

**Issue by alex3165** [danger/danger-js#170]
Is there a way to avoid trying to get the reviews from the API ? I am not using it and my enterprise Github API doesn't have this endpoint. Error message :
```
❯ npm run danger

> lerna-desktop@0.0.0 danger /Users/alexandrer/development/tango/trainline-desktop
> scripts/danger.sh

OK, looks good Fake Testing CI on GitHub
Request failed [404]: https://github.thetrainline.com/api/v3/repos/Tango/trainline-desktop/pulls/752/reviews
Response: {
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/enterprise/2.8/v3"
}
Error:  Error: 404
    at GitHubAPI.<anonymous> (/Users/alexandrer/development/tango/trainline-desktop/node_modules/danger/distribution/api/fetch.js:92:27)
    at step (/Users/alexandrer/development/tango/trainline-desktop/node_modules/danger/distribution/api/fetch.js:32:23)
    at Object.next (/Users/alexandrer/development/tango/trainline-desktop/node_modules/danger/distribution/api/fetch.js:13:53)
    at fulfilled (/Users/alexandrer/development/tango/trainline-desktop/node_modules/danger/distribution/api/fetch.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by alex3165** [comment]
I think https://github.com/danger/danger-js/commit/123cb9d300d5d1210972601ff1de9cb10721b877 is the problem

**Comment by orta** [comment]
This relates to #163 - right now if _any_ API requests fail, then the build fails. However, if GH enterprise doesn't have the new reviews systems, then it'll need to fail and return an empty object/array without failing the build.

Think you can make the error handling move inline?

**Comment by alex3165** [comment]
Hey @orta, I have opened a PR that should improve consistency as discussed in #163 as well.

See: https://github.com/danger/danger-js/pull/173
