### ISSUE TITLE
prs.find is not a function

### ISSUE THREAD

**Issue by deecewan** [danger/danger-js#181]
Just updated to the latest danger (`0.13.0`) and looks like something isn't quite right.

I'm not sure exactly when this call was made, but I am using Codeship.  This may have something to do with API changes that the codeship provider relied on.

```
yarn danger v0.21.3
$ danger 
Error:  TypeError: prs.find is not a function
at Object.<anonymous> (<project>/node_modules/danger/distribution/ci_source/ci_source_helpers.js:90:39)
at step (<project>/node_modules/danger/distribution/ci_source/ci_source_helpers.js:32:23)
at Object.next (<project>/node_modules/danger/distribution/ci_source/ci_source_helpers.js:13:53)
at fulfilled (<project>/node_modules/danger/distribution/ci_source/ci_source_helpers.js:4:58)
at process._tickCallback (internal/process/next_tick.js:109:7)
error Command failed with exit code 1.
```

**Comment by orta** [comment]
Intertesting, could `getPullRequests` ever return a non-array type? In any case, `lodash.find` is in danger dep tree, replacing it with that would be a trivial fix

**Comment by deecewan** [comment]
yeah, that's probably not a bad idea.

I can't see it ever not returning an array, unless the request fails.

**Comment by orta** [comment]
Gonna make a release, so I'll fix this 👍
