### ISSUE TITLE
Unexpected token import when using dangerfile.ts in danger 0.14.1

### ISSUE THREAD

**Issue by macklinu** [danger/danger-js#192]
I'm seeing the following error when attempting to run Danger on a `dangerfile.ts` using danger 0.14.1.

```
$ danger 
OK, everything looks good: Jenkins on GitHub
Error:  dangerfile.ts:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import {includes, startsWith} from "lodash";
                                                                                         ^^^^^^
SyntaxError: Unexpected token import
    at transformAndBuildScript (/var/lib/jenkins/jobs/frontend-pr/workspace/node_modules/jest-runtime/build/transform.js:320:12)
    at module.exports (/var/lib/jenkins/jobs/frontend-pr/workspace/node_modules/jest-runtime/build/transform.js:351:14)
    at Runtime._execModule (/var/lib/jenkins/jobs/frontend-pr/workspace/node_modules/jest-runtime/build/index.js:437:20)
    at Runtime.requireModule (/var/lib/jenkins/jobs/frontend-pr/workspace/node_modules/jest-runtime/build/index.js:296:14)
    at /var/lib/jenkins/jobs/frontend-pr/workspace/node_modules/danger/distribution/runner/DangerfileRunner.js:137:33
    at ensureCleanDangerfile (/var/lib/jenkins/jobs/frontend-pr/workspace/node_modules/danger/distribution/runner/DangerfileRunner.js:177:5)
    at Object.<anonymous> (/var/lib/jenkins/jobs/frontend-pr/workspace/node_modules/danger/distribution/runner/DangerfileRunner.js:136:21)
    at step (/var/lib/jenkins/jobs/frontend-pr/workspace/node_modules/danger/distribution/runner/DangerfileRunner.js:32:23)
    at Object.next (/var/lib/jenkins/jobs/frontend-pr/workspace/node_modules/danger/distribution/runner/DangerfileRunner.js:13:53)
    at /var/lib/jenkins/jobs/frontend-pr/workspace/node_modules/danger/distribution/runner/DangerfileRunner.js:7:71
error Command failed with exit code 1.
```

The imports in my `dangerfile.ts`:

```
import {includes, startsWith} from "lodash";
import {danger, warn} from "danger";
```

I've excluded `dangerfile.ts` from my `tsconfig.json`:

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "jsx": "react",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es6",
    "allowSyntheticDefaultImports": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true
  },
  "exclude": [
    "node_modules",
    "typings/globals",
    "typings/modules",
    "dangerfile.ts"
  ]
}
```

Any suggestions on what I might be overlooking? Any thoughts on if this is a bug or a misconfiguration on my part (need more info)?

/cc @orta

**Comment by orta** [comment]
Do you have Jest set up? E.g. all this stuff

```json
  "jest": {
    "transform": {
      ".(ts|tsx)": "<rootDir>/node_modules/ts-jest/preprocessor.js"
    },
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|tsx|js)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js"
    ]
  }
```

**Comment by orta** [comment]
For example in this PR I made no changes to any parts of the setup for the project: https://github.com/artsy/emission/pull/457/files

**Comment by macklinu** [comment]
Ah, that was the issue. The codebase I migrated `dangerfile.js` to `dangerfile.ts` uses Mocha instead of Jest for testing, so I didn't have any of the Jest configuration in my `package.json`.

The minimum I needed to get CI passing:

- add the `ts-jest` dependency - `yarn add ts-jest --dev`
- add the following to my `package.json`

```json
"jest": {
  "transform": {
    ".(ts|tsx)": "<rootDir>/node_modules/ts-jest/preprocessor.js"
  }
}
```

My issue is resolved, but this could be good information for the README - thoughts?

**Comment by orta** [comment]
IMO, that would be good yeah. Basically it's "Using Jest + TS? Do nothing" "Not using Jest? ^" 👍

**Comment by macklinu** [comment]
Nice, I'll PR that for the README. 😄

**Comment by macklinu** [comment]
Closing this via #193
