### ISSUE TITLE
Running locally without any integration

### ISSUE THREAD

**Issue by adam-moss** [danger/danger-js#308]
Apologies if this is obvious, or has been asked before - I have had an admittedly quick look but can't see anything.

Is there any way to run danger-js locally without trying to "phone home" to github?  I.e. as a simple cli tool that dumps to the console, exit 1 on error type of thing?

I've seen the `DANGER_FAKE_CI` env var which I'd hoped might do this but sadly not 😭 

Longer term Peril is probably the better answer for my particular use case, but again without the github bit.

Thanks

**Comment by orta** [comment]
No afraid not, Danger JS's original vision was to  be entirely API based (so that peril could be built.)  Which has been my main focus when working on it.

I'm definitely open to a new command like `danger local` that uses git commands to generate the DSL. It could pass `null` in for `danger.github` but you can have the entire API for `git` and it's functions working by generating the same diff that github provides. 

I'm assuming the use case would be for something like pre-commit hooks, so I think you'd also need to be able to state the branch to compare against.

**Comment by adam-moss** [comment]
Hmmm... pre-commit wasn't the use case I actually have, but that would be a fair side affect of the same I think.  Downside of that though is you'd probably then want to support multiple dangerfiles depending on how many/complex/timeconsuming rules there were and whether they were relevant at the individual commit stage.

I'll have a gander through the code and see if a direct git api is something I could do 👍

**Comment by orta** [comment]
Aye, there's some discussion on multiple run Danger comments in #196 - some of my apps use a before and after Dangerfile in Ruby due to iOS builds taking forever to compile and run

**Comment by adam-moss** [comment]
If you get a moment could you give me some pointers on what would need to change - can't see the wood for the trees at the moment!  Thanks

**Comment by orta** [comment]
Roughly, you'd need to

* create a [new command](https://github.com/danger/danger-js/blob/master/source/commands/danger-pr.ts) 
* which works with [a new GitCLI Platform](https://github.com/danger/danger-js/blob/master/source/platforms/platform.ts#L31) object to [re-create the git DSL](https://github.com/danger/danger-js/blob/master/source/runner/Executor.ts#L78) using Git
* (you might find something useful in how the [ruby git works](https://github.com/danger/danger/blob/master/lib/danger/scm_source/git_repo.rb))
* You'd need to have a console output version of the commenting part of the Platform interface

**Comment by orta** [comment]
This is easier now: `danger runner` will eval a dangerfile, you just need to generate a DSL compatible with the [DangerDSLJSON](https://github.com/danger/danger-js/blob/master/source/dsl/DangerDSL.ts#L17) class

**Comment by adam-moss** [comment]
Right, now that #473 has landed I'm getting error:

```
Could not get diff from git between master and HEAD
{ Error: stdout maxBuffer exceeded
    at Socket.onChildStdout (child_process.js:325:14)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:252:13)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at Pipe.onread (net.js:599:20) cmd: 'git diff master...HEAD' }
```

For `danger local --dangerfile dangerfile.js`

And also

```
error: unknown option `--base'

Error:  TypeError: Cannot read property 'concat' of undefined
    at Object.exports.mergeResults (/Users/adam.moss/projects/boss/commitlint-config-base/node_modules/danger/distribution/commands/utils/reporting.js:15:33)
    at Object.<anonymous> (/Users/adam.moss/projects/boss/commitlint-config-base/node_modules/danger/distribution/commands/utils/runDangerSubprocess.js:97:51)
    at step (/Users/adam.moss/projects/boss/commitlint-config-base/node_modules/danger/distribution/commands/utils/runDangerSubprocess.js:32:23)
    at Object.next (/Users/adam.moss/projects/boss/commitlint-config-base/node_modules/danger/distribution/commands/utils/runDangerSubprocess.js:13:53)
    at /Users/adam.moss/projects/boss/commitlint-config-base/node_modules/danger/distribution/commands/utils/runDangerSubprocess.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/adam.moss/projects/boss/commitlint-config-base/node_modules/danger/distribution/commands/utils/runDangerSubprocess.js:3:12)
    at ChildProcess.<anonymous> (/Users/adam.moss/projects/boss/commitlint-config-base/node_modules/danger/distribution/commands/utils/runDangerSubprocess.js:85:48)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
```
for `danger local --base develop --dangerfile dangerfile.js`

Any pointers you could share?

**Comment by orta** [comment]
Cool, want to move this to a new issue? I'll forget about it if it's just a comment on a merged PR

**Comment by adam-moss** [comment]
Will do 👍
