### ISSUE TITLE
tests don't work on master - windows

### ISSUE THREAD

**Issue by mlabrum** [danger/danger-js#313]
Hey,

I've checked out this project, attempted to run `npm test` and had the following errors...

```
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\git\forks\danger-js>npm test

> danger@1.0.0 test C:\git\forks\danger-js
> jest

 FAIL  source\platforms\github\_tests\_github_git.test.ts (6.348s)
  ● the dangerfile gitDSL › sets the modified/created/deleted

    Error
      Error: expect(received).toEqual(expected)

      Expected value to equal:
        ["CHANGELOG.md", "data/schema.graphql", "data/schema.json", "externals/metaphysics", "lib/__mocks__/react-relay.js", "lib/components/artist/about.js", "lib/components/gene/header.js", "lib/containers/__tests__/__snapshots__/gene-tests.js.snap", "lib/containers/__tests__/gene-tests.js", "lib/containers/gene.js", "tsconfig.json"]
      Received:
        ["CHANGELOG.md", "data/schema.graphql", "data/schema.json", "externals/metaphysics", "lib/__mocks__/react-relay.js", "lib/components/artist/about.js", "", "lib/components/gene/biography.js", "lib/components/gene/header.js", "lib/components/related_artists/index.js", "lib/components/related_artists/related_artist.js", "lib/containers/__tests__/__snapshots__/gene-tests.js.snap", "lib/containers/__tests__/gene-tests.js", "lib/containers/gene.js", "tsconfig.json"]

      Difference:

      - Expected
      + Received

      @@ -3,11 +3,18 @@
         "data/schema.graphql",
         "data/schema.json",
         "externals/metaphysics",
         "lib/__mocks__/react-relay.js",
         "lib/components/artist/about.js",
      +  "/dev/null",
      +  "/dev/null",
      +  "lib/components/gene/about.js",
",    +  "lib/components/gene/about_gene.js
      +  "lib/components/gene/biography.js",
         "lib/components/gene/header.js",
      +  "lib/components/related_artists/index.js",
      +  "lib/components/related_artists/related_artist.js",
         "lib/containers/__tests__/__snapshots__/gene-tests.js.snap",
         "lib/containers/__tests__/gene-tests.js",
         "lib/containers/gene.js",
         "tsconfig.json",
       ]
      at Object.<anonymous> (source/platforms/github/_tests/_github_git.test.ts:47:43)
      at step (source/platforms/github/_tests/_github_git.test.ts:32:23)
      at Object.next (source/platforms/github/_tests/_github_git.test.ts:13:51)
      at fulfilled (source/platforms/github/_tests/_github_git.test.ts:4:56)
      at process._tickCallback (internal/process/next_tick.js:109:7)

  the dangerfile gitDSL
    × sets the modified/created/deleted (1699ms)
    √ shows the diff for a specific file (50ms)
    √ should include `before` text content of the file (18ms)
    √ should include `after` text content of the file (35ms)
    √ should include `added` text content of the file (23ms)
    √ should include `removed` text content of the file (15ms)
    √ resolves to `null` for files not in modified_files (26ms)
    √ sets up commit data correctly (15ms)
    JSONPatchForFile
      √ returns a null for files not in the modified_files (18ms)
      √ handles showing a patch for two different diff files (13ms)
    JSONDiffForFile
      √ returns an empty object for files not in the modified_files (22ms)
      √ handles showing a patch for two different diff files (16ms)
      √ handles a package.json change elegantly (14ms)

 PASS  source\ci_source\providers\_tests\_circle.test.ts
  being found when looking for CI
    √ finds Circle with the right ENV (4ms)
  .isCI
    √ validates when all Circle environment vars are set (1ms)
    √ does not validate without josh (2ms)
  .isPR
    √ validates when all circle environment vars are set (1ms)
    √ does not validate outside of circle (1ms)
    √ does not validate when CIRCLE_CI_API_TOKEN is missing
    √ does not validate when CIRCLE_PROJECT_USERNAME is missing (1ms)
    √ does not validate when CIRCLE_PROJECT_REPONAME is missing (1ms)
    √ does not validate when CIRCLE_BUILD_NUM is missing (1ms)
    √ needs to have a PR number (3ms)
  .pullReuestID
    √ pulls it out of the env (2ms)
    √ can derive it from PR Url (1ms)
  .repoSlug
    √ derives it from the PR Url (1ms)

 PASS  source\ci_source\providers\_tests\_semaphore.test.ts
  being found when looking for CI
    √ finds Semaphore with the right ENV (4ms)
  .isCI
    √ validates when all Semaphore environment vars are set (1ms)
    √ does not validate without josh (1ms)
  .isPR
    √ validates when all semaphore environment vars are set (1ms)
    √ does not validate outside of semaphore (2ms)
    √ does not validate when SEMAPHORE_CI_API_TOKEN is missing (1ms)
    √ does not validate when SEMAPHORE_PROJECT_USERNAME is missing (1ms)
    √ does not validate when SEMAPHORE_PROJECT_REPONAME is missing (1ms)
    √ does not validate when SEMAPHORE_BUILD_NUM is missing (1ms)
    √ needs to have a PR number (1ms)
  .pullRequestID
    √ pulls it out of the env (1ms)
  .repoSlug
    √ derives it from the PR Url (1ms)


 RUNS  source/runner/_tests/_danger_runner.test.ts
 RUNS  source/runner/_tests/_executor.test.ts
 PASS  source\ci_source\providers\_tests\_travis.test.ts
  being found when looking for CI
    √ finds Travis with the right ENV (5ms)
  .isCI
    √ validates when all Travis environment vars are set and Josh K says so (1ms)
    √ does not validate without josh (1ms)
  .isPR
    √ validates when all Travis environment vars are set and Josh K says so (2ms)
    √ does not validate without josh (1ms)
    √ does not validate when TRAVIS_PULL_REQUEST is missing (1ms)
    √ does not validate when TRAVIS_REPO_SLUG is missing (1ms)
    √ needs to have a PR number

 RUNS  source/runner/_tests/_danger_runner.test.ts
 RUNS  source/runner/_tests/_executor.test.ts
 RUNS  source/ci_source/providers/_tests/_travis.test.ts

Test Suites: 1 failed, 2 passed, 3 of 20 total
Tests:       1 failed, 37 passed, 38 total
Snapshots:   5 passed, 5 total
Time:        10s, estimated 101s
  console.error source\runner\Executor.ts:264
    { Error: ENOENT: no such file or directory, open ''
        at Object.fs.openSync (fs.js:583:18)
        at Object.fs.readFileSync (fs.js:490:33)
        at ensureCleanDangerfile (C:\git\forks\danger-js\source\runner\DangerfileRunner.ts:171:31)
        at Object.<anonymous> (C:\git\forks\danger-js\source\runner\DangerfileRunner.ts:132:21)
        at step (C:\git\forks\danger-js\source\runner\DangerfileRunner.ts:32:23)
        at Object.next (C:\git\forks\danger-js\source\runner\DangerfileRunner.ts:13:51)
  .pullRequestIDt\forks\danger-js\source\runner\DangerfileRunner.ts:7:71
    √ pulls it out of the env (1ms)
  .repoSlug
    √ pulls it out of the env (1ms)


 RUNS  source/ci_source/_tests/_get_ci_source.test.ts
 RUNS  source/runner/_tests/_danger_runner.test.ts
 RUNS  source/runner/_tests/_executor.test.ts

Test Suites: 1 failed, 3 passed, 4 of 20 total
Tests:       1 failed, 47 passed, 48 total
Snapshots:   5 passed, 5 total
Time:        11s, estimated 101s
  console.log source\runner\Executor.ts:221
    No issues or messages were sent. Removing any existing messages.

  console.log source\runner\Executor.ts:236
    Found only warnings, not failing the build.

 PASS  source\runner\_tests\_executor.test.ts (8.843s)
  setup
    √ gets diff / pr info in setup (17ms)
    √ gets diff / pr info / utils in setup (7ms)
    √ Creates a DangerResults for a raising dangerfile (91ms)
    √ Deletes a post when there are no messages (55ms)
    √ Updates or Creates comments for warnings (9ms)
    √ Updates or Creates comments for warnings (3ms)
    √ Updates the status with success for a passed results (9ms)
    √ Updates the status with success for a passed results (4ms)


 RUNS  source/ci_source/_tests/_get_ci_source.test.ts
 RUNS  source/runner/_tests/_danger_runner.test.ts
 PASS  source\ci_source\_tests\_get_ci_source.test.tsest.ts
  .getCISourceForEnv
    √ returns undefined if nothing is found (4ms)
    √ falls back to the fake if DANGER_FAKE_CI exists (2ms)
  .getCISourceForExternal
    √ should resolve module relatively (2ms)
    √ should return undefined if module resolution fails (25ms)

 PASS  source\platforms\github\_tests\_github_utils.test.ts
  fileLinks
    √ Should convert a few paths into links (7ms)
    √ Should convert a few paths into links showing full links (1ms)
    √ Should convert a few paths into links showing full link on a custom fork/branch (2ms)

 PASS  source\ci_source\providers\_tests\_jenkins.test.ts
  being found when looking for CI
    √ finds Jenkins with the right ENV (7ms)
  .isCI
    √ validates when JENKINS_URL is present in environment (1ms)
    √ does not validate without JENKINS_URL (1ms)
  .isPR
    √ validates when all Jenkins environment variables are set (1ms)
    √ does not validate with required environment variables (1ms)
    √ does not validate when JENKINS_URL is missing (2ms)
    √ does not validate when ghprbPullId is missing (1ms)
    √ does not validate when ghprbGhRepository is missing (9ms)
    √ needs to have a PR number (2ms)
  .pullRequestID
    √ pulls it out of environment (4ms)
  .repoSlug
    √ pulls it out of environment (3ms)

 PASS  source\runner\templates\_tests\_githubIssueTemplates.test.ts
  generating messages
    √ shows no tables for empty results (8ms)
    √ shows no tables for results without messages (2ms)
    √ Shows the failing messages in a table (1ms)
    √ Shows the warning messages in a table (1ms)
    √ does not break commonmark rules around line breaks (1ms)
    √ Should include summary on top of message (1ms)
    √ leaves space between <td>s to allow GitHub to render message content as markdown (5ms)

 PASS  source\commands\utils\_tests\file-utils.test.ts
  dangerfilePath
    √ should return anything passed into the program's dangerfile (4ms)
    √ should find a dangerfile.js if there is no program, and the .js file exists (2ms)
    √ should find a dangerfile.ts if there is no program, and the .js file does not exist (4ms)
    √ should raise if nothing exists (1ms)

 PASS  source\platforms\github\_tests\_pull_request_parser.test.ts
  parsing urls
    √ handles bad data (6ms)
    √ pulls out the repo / pr ID (7ms)
    √ handles query params too (2ms)

 PASS  source\ci_source\providers\_tests\_dockerCloud.test.ts
  being found when looking for CI
    √ finds DockerCloud with the right ENV (3ms)
  .isCI
    √ validates when all DockerCloud environment vars are set (1ms)
    √ does not validate without env (1ms)
  .isPR
    √ validates when all dockerCloud environment vars are set (1ms)
    √ does not validate outside of dockerCloud (1ms)
    √ does not validate when PULL_REQUEST_URL is missing (1ms)
    √ does not validate when SOURCE_REPOSITORY_URL is missing (1ms)
    √ does not validate when DOCKER_REPO is missing (1ms)
  .pullRequestID
    √ pulls it out of the env (1ms)
  .repoSlug
    √ derives it from the PR Url (1ms)

 PASS  source\ci_source\providers\_tests\_drone.test.ts
  being found when looking for CI
    √ finds Drone with the right ENV (4ms)
  .isCI
    √ validates when all Drone environment vars are set (2ms)
    √ does not validate without DRONE (1ms)
  .isPR
    √ validates when all Drone environment vars are set (1ms)
    √ does not validate without DRONE_PULL_REQUEST (1ms)
    √ does not validate when DRONE_PULL_REQUEST is missing (1ms)
    √ does not validate when DRONE_REPO is missing (1ms)
    √ needs to have a PR number (6ms)
  .pullRequestID
    √ pulls it out of the env (1ms)
  .repoSlug
    √ pulls it out of the env


 RUNS  source/platforms/_tests/_platform.test.ts
 RUNS  source/runner/_tests/_danger_runner.test.ts
 RUNS  source/ci_source/providers/_tests/_buildkite.test.ts

Test Suites: 1 failed, 12 passed, 13 of 20 total
 PASS  source\platforms\_tests\_platform.test.ts
  √ should bail if there is no DANGER_GITHUB_API_TOKEN found (83ms)

 PASS  source\ci_source\providers\_tests\_buildkite.test.ts
  being found when looking for CI
    √ finds Buildkite with the right ENV (4ms)
  .isCI
    √ validates when all Buildkite environment vars are set (2ms)
    √ does not validate without env (1ms)
  .isPR
    √ validates when all buildkite environment vars are set (1ms)
    √ does not validate outside of buildkite (1ms)
    √ does not validate when BUILDKITE_PULL_REQUEST is missing (2ms)
    √ does not validate when BUILDKITE_REPO is missing (1ms)
    √ does not validate when BUILDKITE is missing
  .pullRequestID
    √ pulls it out of the env (1ms)
  .repoSlug
    √ derives it from the repo URL (3ms)
    √ derives it from the repo URL in SSH format (1ms)

 PASS  source\ci_source\providers\_tests\_buddyBuild.test.ts
  being found when looking for CI
    √ finds BuddyBuild with the right ENV (4ms)
  .isCI
    √ validates when all BuddyBuild environment vars are set (1ms)
    √ does not validate (1ms)
  .isPR
    √ validates when all BuddyBuild environment vars are set (2ms)
    √ does not validate outside of BuddyBuild (2ms)
    √ does not validate when BUDDYBUILD_REPO_SLUG is missing (1ms)
    √ needs to have a PR number (3ms)
    √ does not validate when BUDDYBUILD_PULL_REQUEST is missing (1ms)
    √ needs to have a PR number (1ms)
  .pullRequestID
    √ pulls it out of the env (1ms)
  .repoSlug
    √ pulls it out of the env (1ms)

 PASS  source\runner\_tests\_danger_utils.test.ts
  sentence()
    √ handles falsy input (4ms)
    √ handles empty array (2ms)
    √ handles array with one item (1ms)
    √ handles array with multiple items (1ms)
  href()
    √ returns null when href and text are falsy (1ms)
    √ returns just the text when the href is missing (1ms)
    √ returns <a> tag with href as text when text is missing (1ms)
    √ returns <a> tag for supplied href and text (2ms)

 FAIL  source\platforms\github\_tests\_github_api.test.ts
  ● Test suite failed to run

    C:/git/forks/danger-js/source/platforms/_tests/_github.test.ts: babel-plugin-jest-hoist: The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.
    Invalid variable access: __awaiter
    Whitelisted objects: Array, ArrayBuffer, Boolean, DataView, Date, Error, EvalError, Float32Array, Float64Array, Function, Generator, GeneratorFunction, Infinity, Int16Array, Int32Array, Int8Array, InternalError, Intl, JSON, Map, Math, NaN, Number, Object, Promise, Proxy, RangeError, ReferenceError, Reflect, RegExp, Set, String, Symbol, SyntaxError, TypeError, URIError, Uint16Array, Uint32Array, Uint8Array, Uint8ClampedArray, WeakMap, WeakSet, arguments, expect, jest, require, undefined, DTRACE_NET_SERVER_CONNECTION, DTRACE_NET_STREAM_END, DTRACE_HTTP_SERVER_REQUEST, DTRACE_HTTP_SERVER_RESPONSE, DTRACE_HTTP_CLIENT_REQUEST, DTRACE_HTTP_CLIENT_RESPONSE, COUNTER_NET_SERVER_CONNECTION, COUNTER_NET_SERVER_CONNECTION_CLOSE, COUNTER_HTTP_SERVER_REQUEST, COUNTER_HTTP_SERVER_RESPONSE, COUNTER_HTTP_CLIENT_REQUEST, COUNTER_HTTP_CLIENT_RESPONSE, global, process, Buffer, clearImmediate, clearInterval, clearTimeout, setImmediate, setInterval, setTimeout, console, __core-js_shared__.
    Note: This is a precaution to guard against uninitialized mock variables. If it is ensured that the mock is required lazily, variable names prefixed with `mock` are permitted.

      at invariant (node_modules/babel-plugin-jest-hoist/build/index.js:13:11)
      at newFn (node_modules/babel-traverse/lib/visitors.js:276:21)
      at NodePath._call (node_modules/babel-traverse/lib/path/context.js:76:18)
      at NodePath.call (node_modules/babel-traverse/lib/path/context.js:48:17)
      at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:105:12)
      at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:150:16)
      at TraversalContext.visitMultiple (node_modules/babel-traverse/lib/context.js:103:17)
      at TraversalContext.visit (node_modules/babel-traverse/lib/context.js:190:19)

 FAIL  source\platforms\_tests\_github.test.ts
  ● Test suite failed to run

    C:/git/forks/danger-js/source/platforms/_tests/_github.test.ts: babel-plugin-jest-hoist: The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.
    Invalid variable access: __awaiter
    Whitelisted objects: Array, ArrayBuffer, Boolean, DataView, Date, Error, EvalError, Float32Array, Float64Array, Function, Generator, GeneratorFunction, Infinity, Int16Array, Int32Array, Int8Array, InternalError, Intl, JSON, Map, Math, NaN, Number, Object, Promise, Proxy, RangeError, ReferenceError, Reflect, RegExp, Set, String, Symbol, SyntaxError, TypeError, URIError, Uint16Array, Uint32Array, Uint8Array, Uint8ClampedArray, WeakMap, WeakSet, arguments, expect, jest, require, undefined, DTRACE_NET_SERVER_CONNECTION, DTRACE_NET_STREAM_END, DTRACE_HTTP_SERVER_REQUEST, DTRACE_HTTP_SERVER_RESPONSE, DTRACE_HTTP_CLIENT_REQUEST, DTRACE_HTTP_CLIENT_RESPONSE, COUNTER_NET_SERVER_CONNECTION, COUNTER_NET_SERVER_CONNECTION_CLOSE, COUNTER_HTTP_SERVER_REQUEST, COUNTER_HTTP_SERVER_RESPONSE, COUNTER_HTTP_CLIENT_REQUEST, COUNTER_HTTP_CLIENT_RESPONSE, global, process, Buffer, clearImmediate, clearInterval, clearTimeout, setImmediate, setInterval, setTimeout, console, __core-js_shared__.
    Note: This is a precaution to guard against uninitialized mock variables. If it is ensured that the mock is required lazily, variable names prefixed with `mock` are permitted.

      at invariant (node_modules/babel-plugin-jest-hoist/build/index.js:13:11)
      at newFn (node_modules/babel-traverse/lib/visitors.js:276:21)
      at NodePath._call (node_modules/babel-traverse/lib/path/context.js:76:18)
      at NodePath.call (node_modules/babel-traverse/lib/path/context.js:48:17)
      at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:105:12)
      at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:150:16)
      at TraversalContext.visitMultiple (node_modules/babel-traverse/lib/context.js:103:17)
      at TraversalContext.visit (node_modules/babel-traverse/lib/context.js:190:19)


 RUNS  source/runner/_tests/_danger_runner.test.ts

Test Suites: 3 failed, 16 passed, 19 of 20 total
 PASS  source\runner\_tests\_danger_runner.test.ts (135.695s)
  √ creates a working jest config (21ms)
  with fixtures
    √ handles a blank Dangerfile (15379ms)
    √ handles a full set of messages (40ms)
    √ handles a failing dangerfile (36ms)
    √ handles relative imports correctly (138ms)
    √ handles scheduled (async) code (62ms)
    √ handles multiple scheduled statements and all message types (161ms)
    √ can schedule callback-based promised (29ms)
    √ can handle TypeScript based Dangerfiles (109689ms)
    √ can handle a plugin (which is already used in Danger) (2460ms)
  cleaning Dangerfiles
    √ Supports removing the danger import (4ms)
    √ also handles typescript style imports (1ms)
    √ also handles require style imports

Test Suites: 3 failed, 17 passed, 20 total
Tests:       1 failed, 151 passed, 152 total
Snapshots:   7 passed, 7 total
Time:        137.991s
Ran all test suites.
npm ERR! Test failed.  See above for more details.

C:\git\forks\danger-js>
```

I've fixed a semi colon issue on windows here: https://github.com/danger/danger-js/pull/312 but haven't had any time to look into the other issues here

Node 7.7.0, Node 8.2.1 (upgraded to see if that would change things, it didn't... though the tests did go faster)
NPM 5.3.0

Thanks

**Comment by orta** [comment]
Fixed by #312

**Comment by mlabrum** [comment]
Hey, 

I still haven't figured out what is causing 
```C:/git/forks/danger-js/source/platforms/_tests/_github.test.ts: babel-plugin-jest-hoist: The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.
    Invalid variable access: __awaiter
    Whitelisted objects: Array, ArrayBuffer, Boolean, DataView, Date, Error, EvalError, Float32Array, Float64Array, Function, Generator, GeneratorFunction, Infinity, Int16Array, Int32Array, Int8Array, InternalError, Intl, JSON, Map, Math, NaN, Number, Object, Promise, Proxy, RangeError, ReferenceError, Reflect, RegExp, Set, String, Symbol, SyntaxError, TypeError, URIError, Uint16Array, Uint32Array, Uint8Array, Uint8ClampedArray, WeakMap, WeakSet, arguments, expect, jest, require, undefined, DTRACE_NET_SERVER_CONNECTION, DTRACE_NET_STREAM_END, DTRACE_HTTP_SERVER_REQUEST, DTRACE_HTTP_SERVER_RESPONSE, DTRACE_HTTP_CLIENT_REQUEST, DTRACE_HTTP_CLIENT_RESPONSE, COUNTER_NET_SERVER_CONNECTION, COUNTER_NET_SERVER_CONNECTION_CLOSE, COUNTER_HTTP_SERVER_REQUEST, COUNTER_HTTP_SERVER_RESPONSE, COUNTER_HTTP_CLIENT_REQUEST, COUNTER_HTTP_CLIENT_RESPONSE, global, process, Buffer, clearImmediate, clearInterval, clearTimeout, setImmediate, setInterval, setTimeout, console, __core-js_shared__.
    Note: This is a precaution to guard against uninitialized mock variables. If it is ensured that the mock is required lazily, variable names prefixed with `mock` are permitted.
```

Cheers

**Comment by orta** [comment]
This is weird, any idea why this isn't failing on CI? We have AppVeyor making windows builds

**Comment by orta** [comment]
Also, could it be an `npm install` vs `yarn install` issue?

**Comment by orta** [comment]
I'm gonna call this as OK - we have tests running on windows every PR/commit now
