### ISSUE TITLE
Error when using warn within an async function

### ISSUE THREAD

**Issue by alexjfno1** [danger/danger-js#389]
I have a `dangerfile.js` which contains:

```javascript
import { schedule, warn } from "danger";

const asyncFunction = async () { ... };

schedule(async () => {
  await asyncFunction();
  message('You havent formated the code using prettier. Please run npm run format before merging the PR');
});
```

When I run it though I get the error:

```bash
{
  fails: [
    {
      message: "Danger failed to run `dangerfile.js`."
    }
  ],
  warnings: [],
  markdowns: ["## Error Error

Operation not allowed on contextified object.
Error: Operation not allowed on contextified object.
    at Object.setPrototypeOf (/Users/af/NS/simulado/node_modules/vm2/lib/contextify.js:195:11)
    at Function.setPrototypeOf (<anonymous>)
    at Object.runtime.mark (/Users/af/NS/simulado/node_modules/danger/node_modules/regenerator-runtime/runtime.js:134:14)
    at Object.apply (/Users/alexf/NS/simulado/node_modules/vm2/lib/contextify.js:288:34)
    at Object.<anonymous> (/Users/alexf/NOTHS/simulado/dangerfile.js:43:61)
    at NodeVM.run (/Users/alexf/NS/simulado/node_modules/vm2/lib/main.js:426:27)
    at Object.<anonymous> (/Users/af/NS/simulado/node_modules/danger/distribution/runner/DangerfileRunner.js:160:24)
    at step (/Users/af/NS/simulado/node_modules/danger/distribution/runner/DangerfileRunner.js:40:23)
    at Object.next (/Users/af/NS/simulado/node_modules/danger/distribution/runner/DangerfileRunner.js:21:53)
    at fulfilled (/Users/af/NS/simulado/node_modules/danger/distribution/runner/DangerfileRunner.js:12:58)

### Dangerfile

--------------^

  "],
  messages: []
}
```

Any idea's as to why it's failing?

**Comment by orta** [comment]
Yes - it's some of the sandboxing I've been trying to clean up with https://github.com/danger/danger-js/pull/378 and https://github.com/danger/danger-js/issues/373

It's on my TODO, but generally speaking the code generated by using async functions https://github.com/danger/danger-js/issues/373 triggers the sandbox in vm2 to fail. I'd rather remove the sandbox completely for the moment.

**Comment by orta** [comment]
If you can, [try move that async code into a plugin](http://danger.systems/js/usage/extending-danger.html) and it'll be fine today

**Comment by alexjfno1** [comment]
@orta Any idea when it's likely to be fixed?

**Comment by orta** [comment]
Nope, I work on DangerJS in my spare time, so it's hard to offer any schedule - there's a PR https://github.com/danger/danger-js/pull/378, but it's still failing

**Comment by orta** [comment]
Try see if alpha 20 fixes this 👍

**Comment by alexjfno1** [comment]
@orta Great that worked!

I'm not sure if this is related but now when I run it on CircleCI I get `Error: Cannot find module 'color-convert'`

**Comment by alexjfno1** [comment]
It seems `Error: Cannot find module 'color-convert'` was a random failure. Everything seems to be working now.
