### ISSUE TITLE
Passed 2 releases broken (2.1.7 and 2.1.8)

### ISSUE THREAD

**Issue by GantMan** [danger/danger-js#463]
```bash
gantman@Gants-iMac: ~/Documents/Projects/playground/solidarity danger_changer!
 $ npm i danger@2.1.6 -g                                                                                                                       [13:18:05]
/usr/local/bin/danger-process -> /usr/local/lib/node_modules/danger/distribution/commands/danger-process.js
/usr/local/bin/danger-pr -> /usr/local/lib/node_modules/danger/distribution/commands/danger-pr.js
/usr/local/bin/danger-run -> /usr/local/lib/node_modules/danger/distribution/commands/danger-run.js
/usr/local/bin/danger-init -> /usr/local/lib/node_modules/danger/distribution/commands/danger-init.js
/usr/local/bin/danger -> /usr/local/lib/node_modules/danger/distribution/commands/danger.js
+ danger@2.1.6
added 6 packages, removed 8 packages and updated 6 packages in 4.233s

gantman@Gants-iMac: ~/Documents/Projects/playground/solidarity danger_changer!
 $ danger pr https://github.com/infinitered/solidarity/pull/154 -d dangerfile.js                                                               [13:18:14]
{
  fails: [],
  warnings: [],
  messages: [
    {
      message: ":tada:, this worked @GantMan"
    }
  ],
  markdowns: [],
  scheduled: []
}

gantman@Gants-iMac: ~/Documents/Projects/playground/solidarity danger_changer!
 $ npm i danger@2.1.7 -g                                                                                                                       [13:18:19]
/usr/local/bin/danger -> /usr/local/lib/node_modules/danger/distribution/commands/danger.js
/usr/local/bin/danger-pr -> /usr/local/lib/node_modules/danger/distribution/commands/danger-pr.js
/usr/local/bin/danger-process -> /usr/local/lib/node_modules/danger/distribution/commands/danger-process.js
/usr/local/bin/danger-run -> /usr/local/lib/node_modules/danger/distribution/commands/danger-run.js
/usr/local/bin/danger-init -> /usr/local/lib/node_modules/danger/distribution/commands/danger-init.js
+ danger@2.1.7
added 1 package and updated 1 package in 3.443s

gantman@Gants-iMac: ~/Documents/Projects/playground/solidarity danger_changer!
 $ danger pr https://github.com/infinitered/solidarity/pull/154 -d dangerfile.js                                                               [13:18:28]
module.js:529
    throw err;
    ^

Error: Cannot find module '../runner/Dangerfile'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/danger/distribution/runner/Executor.js:38:20)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
FAIL

gantman@Gants-iMac: ~/Documents/Projects/playground/solidarity danger_changer!
 $ npm i danger@2.1.8 -g                                                                                                                       [13:18:31]
/usr/local/bin/danger-pr -> /usr/local/lib/node_modules/danger/distribution/commands/danger-pr.js
/usr/local/bin/danger -> /usr/local/lib/node_modules/danger/distribution/commands/danger.js
/usr/local/bin/danger-process -> /usr/local/lib/node_modules/danger/distribution/commands/danger-process.js
/usr/local/bin/danger-run -> /usr/local/lib/node_modules/danger/distribution/commands/danger-run.js
/usr/local/bin/danger-init -> /usr/local/lib/node_modules/danger/distribution/commands/danger-init.js
+ danger@2.1.8
updated 1 package in 3.218s

gantman@Gants-iMac: ~/Documents/Projects/playground/solidarity danger_changer!
 $ danger pr https://github.com/infinitered/solidarity/pull/154 -d dangerfile.js                                                               [13:18:54]
^C%
```
That last one hangs, which I first caught here:  https://github.com/orta/danger-plugin-spellcheck/issues/12

I'll try to use 2.1.6 for now but would love to use TypeScript.  Sorry to file a ticket and have no clue what the issue is.  If I did, I'd help fix it.

**Comment by hawkrives** [comment]
I've noticed that `danger-pr@2.1.8` seems to get stuck in an infinite loop of invoking itself, until it runs out of GitHub api calls. I was trying to debug it, but I couldn't figure out how `danger pr` actually invokes the `distribution/commands/danger-pr.js` script, so… I wound up actually calling `node_modules/danger/distribution/commands/danger-run.js` from my script, instead of the normal entry point.

I meant to file an issue for it yesterday, sorry. I'm game to help debug something if needed!

**Comment by orta** [comment]
Yeah, https://github.com/danger/danger-js/pull/462 will fix it. We've been having issues with commander (and as it's not actively maintained, I don't really want to start sending fixes their way )

I'll take over the PR and try ship it early this week

**Comment by orta** [comment]
Now I get where my mental model was off. Commander mutates `process.argv` which is bonkers to me.

**Comment by GantMan** [comment]
If you ever want to try moving to gluegun CLI beta (what Solidarity is written in) I bet we could help.

Gluegun is about to release 2.0 which is 100% TypeScript.

**Comment by orta** [comment]
3.0 should fix this, I've been testing it on facebook/react 

I would love to use gluegun, but it's a much bigger dependency than Danger needs today - I'll keep my eyes out in the future though - thanks!
