### ISSUE TITLE
Invalid Mapping

### ISSUE THREAD

**Issue by adarlocker** [danger/danger-js#501]
I'm getting this error when trying to run danger (both 'danger pr' and 'danger ci'):

```
Error:  { Error: dangerfile.js: Invalid mapping: {"generated":{"line":3,"column":0},"source":null,"original":{"line":1,"column":0}}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/adarlocker/Documents/gefen/node_modules/source-map/lib/source-map-generator.js:289:13)
    at SourceMapGenerator_addMapping [as addMapping] (/Users/adarlocker/Documents/gefen/node_modules/source-map/lib/source-map-generator.js:101:16)
    at Array.forEach (<anonymous>)
    at SourceMap.get (/Users/adarlocker/Documents/gefen/node_modules/babel-generator/lib/source-map.js:49:25)
    at Object.get [as map] (/Users/adarlocker/Documents/gefen/node_modules/babel-generator/lib/buffer.js:53:33)
    at File.generate (/Users/adarlocker/Documents/gefen/node_modules/babel-core/lib/transformation/file/index.js:710:26)
    at File.transform (/Users/adarlocker/Documents/gefen/node_modules/babel-core/lib/transformation/file/index.js:554:17)
    at /Users/adarlocker/Documents/gefen/node_modules/babel-core/lib/transformation/pipeline.js:50:19
    at File.wrap (/Users/adarlocker/Documents/gefen/node_modules/babel-core/lib/transformation/file/index.js:564:16)
    at Pipeline.transform (/Users/adarlocker/Documents/gefen
```

The only solution I could find for now (and only locally) is commenting the relevant lines inside node_modules (bolded):

```
SourceMapGenerator.prototype.addMapping =
    function SourceMapGenerator_addMapping(aArgs) {
        var generated = util.getArg(aArgs, 'generated');
        var original = util.getArg(aArgs, 'original', null);
        var source = util.getArg(aArgs, 'source', null);
        var name = util.getArg(aArgs, 'name', null);

        **// if (!this._skipValidation) {
        //   this._validateMapping(generated, original, source, name);
        // }**

        if (source != null) {
            source = String(source);
            if (!this._sources.has(source)) {
                this._sources.add(source);
            }
        }

        if (name != null) {
            name = String(name);
            if (!this._names.has(name)) {
                this._names.add(name);
            }
        }

        this._mappings.add({
            generatedLine: generated.line,
            generatedColumn: generated.column,
            originalLine: original != null && original.line,
            originalColumn: original != null && original.column,
            source: source,
            name: name
        });
    };
```
Any suggestions? Is it a known issue? I couldn't find any open issue related.

**Comment by orta** [comment]
I've never seen this personally, looks related to the transformation, what does your dangerfile look like?

**Comment by adarlocker** [comment]
`const includes = require('lodash').includes;

const mobileEndpoints = ['package.json']
const mobileRelatedFiles = includes(danger.git.modified_files, mobileEndpoints);

if (mobileRelatedFiles) {
    const message = 'Changes were made to package.json, but not to yarn.lock';
    const idea = 'Perhaps you need to run `yarn install`?';
    warn(`${message} - <i>${idea}</i>`);
}

`

**Comment by orta** [comment]
Yeah, nothing stands out. Babel config related to source maps?

**Comment by adarlocker** [comment]
This is my babelrc file: 

`{
  "sourceMaps": "inline",
  "presets": [
    [
      "env",
      {
        "targets": {
          "node": "current"
        }
      }
    ]
  ],
  "plugins": [
    "transform-object-rest-spread"
  ]
}
`

**Comment by orta** [comment]
Can you try without the source maps? Have you tried anything?

**Comment by adarlocker** [comment]
Adding  "ignore": "dangerfile.js" will work :)

**Comment by orta** [comment]
👍 thanks

**Comment by orta** [comment]
Gonna leave this open as there is work in here in theory, maybe the babelrc passed to danger's transformers should remove the sourcemaps option?

**Comment by ozsay** [comment]
will be best if `danger-js` won't perform preprocessing (by default) on the `Dangerfile.js` as most of the dev tools do.

**Comment by orta** [comment]
Thanks for your opinion, but I don't agree, I'd expect to be able to use the same babel setup in the Dangerfile as the rest of your app.
