### ISSUE TITLE
Tests are failing locally

### ISSUE THREAD

**Issue by gr2m** [danger/danger-js#528]
👋 Hello there

I’m maintaining `@octokit/rest` and testing new releases with popular dependants to reduce the chance that we break projects like `danger-js` with new releases. But when I run the tests, I get an error right now that I'm quite sure is unrelated to changes in `@octokit/rest`: 

<details>
<summary><code>Cannot find module 'vm2' from 'vm2.ts'</code></summary>

```
$ yarn test
yarn run v1.3.2
$ jest
 PASS  source/api/_tests/fetch.test.ts
  ● Console

    console.warn source/api/fetch.ts:66
      Request failed [500]: http://localhost:30001/
    console.warn source/api/fetch.ts:71
      Response: {
        "key": "valid json"
      }
    console.warn source/api/fetch.ts:66
      Request failed [500]: http://localhost:30001/
    console.warn source/api/fetch.ts:73
      Response: any plain text response

 PASS  source/platforms/_tests/_github.test.ts
 PASS  source/runner/runners/utils/_tests/_transpiler.test.ts
 PASS  source/runner/_tests/_executor.test.ts
  ● Console

    console.error source/runner/Executor.ts:214
      Danger has errored
    console.error source/runner/Executor.ts:215
      { Error: ENOENT: no such file or directory, open ''
          at Object.fs.openSync (fs.js:663:18)
          at Object.fs.readFileSync (fs.js:568:33)
          at Object.<anonymous> (/Users/gregor/Projects/octokit/rest-test-repos/danger-js/source/runner/runners/inline.ts:88:63)
          at step (/Users/gregor/Projects/octokit/rest-test-repos/danger-js/source/runner/runners/inline.ts:32:23)
          at Object.next (/Users/gregor/Projects/octokit/rest-test-repos/danger-js/source/runner/runners/inline.ts:13:51)
          at /Users/gregor/Projects/octokit/rest-test-repos/danger-js/source/runner/runners/inline.ts:7:71
          at new Promise (<anonymous>)
          at Object.<anonymous>.__awaiter (/Users/gregor/Projects/octokit/rest-test-repos/danger-js/source/runner/runners/inline.ts:3:12)
          at Object.runDangerfileEnvironment (/Users/gregor/Projects/octokit/rest-test-repos/danger-js/source/runner/runners/inline.ts:69:12)
          at Executor.<anonymous> (/Users/gregor/Projects/octokit/rest-test-repos/danger-js/source/runner/Executor.ts:112:58) errno: -2, code: 'ENOENT', syscall: 'open', path: '' }
    console.log source/runner/Executor.ts:188
      Failing the build, there is 1 fail.
    console.log source/runner/Executor.ts:182
      No issues or messages were sent. Removing any existing messages.
    console.log source/runner/Executor.ts:194
      Found only warnings, not failing the build.
    console.log source/runner/Executor.ts:194
      Found only warnings, not failing the build.
    console.log source/runner/Executor.ts:194
      Found only warnings, not failing the build.
    console.log source/runner/Executor.ts:188
      Failing the build, there is 1 fail.
    console.log source/runner/Executor.ts:188
      Failing the build, there is 1 fail.

 PASS  source/runner/_tests/jsonToDSL.test.ts
 PASS  source/platforms/github/_tests/_github_git.test.ts
 PASS  source/ci_source/providers/_tests/_semaphore.test.ts
 PASS  source/ci_source/providers/_tests/_buildkite.test.ts
 PASS  source/ci_source/providers/_tests/_drone.test.ts
 PASS  source/runner/_tests/json-to-context.test.ts
 PASS  source/ci_source/providers/_tests/_circle.test.ts
 PASS  source/ci_source/providers/_tests/_dockerCloud.test.ts
 PASS  source/ci_source/providers/_tests/_buddyBuild.test.ts
 PASS  source/ci_source/_tests/_get_ci_source.test.ts
  ● Console

    console.error source/ci_source/get_ci_source.ts:30
      could not load CI provider at ./dummy_ci.js due to Error: ENOENT: no such file or directory, stat '/Users/gregor/Projects/octokit/rest-test-repos/danger-js/dummy_ci.js'

 PASS  source/platforms/github/_tests/_github_api.test.ts
 PASS  source/ci_source/providers/_tests/_vsts.test.ts
 PASS  source/ci_source/providers/_tests/_jenkins.test.ts
 PASS  source/platforms/_tests/_platform.test.ts
  ● Console

    console.error source/platforms/platform.ts:61
      The DANGER_GITHUB_API_TOKEN environmental variable is missing
    console.error source/platforms/platform.ts:62
      Without an api token, danger will be unable to comment on a PR

 PASS  source/runner/templates/_tests/_githubIssueTemplates.test.ts
 PASS  source/ci_source/providers/_tests/_nevercode.test.ts
 PASS  source/ci_source/providers/_tests/_travis.test.ts
 PASS  source/platforms/github/_tests/_github_utils.test.ts
 PASS  source/ci_source/providers/_tests/_bitrise.test.ts
 PASS  source/commands/utils/_tests/dangerRunToRunnerCLI.test.ts
 PASS  source/platforms/github/_tests/_pull_request_parser.test.ts
 PASS  source/runner/runners/_tests/_cleanDangerfile.test.ts
 PASS  source/commands/utils/_tests/file-utils.test.ts
 PASS  source/runner/_tests/_danger_utils.test.ts
 PASS  source/platforms/git/_tests/localGetCommits.test.ts
 FAIL  source/runner/runners/_tests/vm2.test.ts
  ● Test suite failed to run

    Cannot find module 'vm2' from 'vm2.ts'

      44 |   const vm = new NodeVM(environment)
      45 | 
    > 46 |   // Require our dangerfile
      47 |   originalContents = originalContents || fs.readFileSync(filename, "utf8")
      48 |   let content = cleanDangerfile(originalContents)
      49 | 
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (source/runner/runners/vm2.ts:46:13)

Summary of all failing tests
 FAIL  source/runner/runners/_tests/vm2.test.ts
  ● Test suite failed to run

    Cannot find module 'vm2' from 'vm2.ts'

      44 |   const vm = new NodeVM(environment)
      45 | 
    > 46 |   // Require our dangerfile
      47 |   originalContents = originalContents || fs.readFileSync(filename, "utf8")
      48 |   let content = cleanDangerfile(originalContents)
      49 | 
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (source/runner/runners/vm2.ts:46:13)


Test Suites: 1 failed, 29 passed, 30 total
Tests:       229 passed, 229 total
Snapshots:   6 passed, 6 total
Time:        6.128s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>

Any idea how I could get that fixed?

**Comment by orta** [comment]
Interesting, it's there in the dependencies ( `"vm2": "patriksimek/vm2#custom_files",`) and I  just tried a fresh clone:

```sh
git clone https://github.com/danger/danger-js.git danger-js2
cd danger-js2
yarn
yarn jest
```

And got a successful test run, could it be a node version difference (I'm on v8.9.3 )

**Comment by gr2m** [comment]
I used v8.9.1 but `yarn` was outdated. Now tests are passing, I just see some error messages, just fyi. Thanks

<details>
<summary> Error messages
<ul>
<li><code>Unable to evaluate the Dangerfile</code></li>
<li><code>could not load CI provider at ./dummy_ci.js due to Error: ENOENT: no such file or directory, stat '/Users/gregor/Projects/octokit/rest-test-repos/danger-js2/dummy_ci.js'</code></li>
<li><code>The DANGER_GITHUB_API_TOKEN environmental variable is missing</code></li>
<li><code>Without an api token, danger will be unable to comment on a PR</code></li>
</ul>
</summary>

```
$ yarn jest
yarn run v1.5.1
$ /Users/gregor/Projects/octokit/rest-test-repos/danger-js2/node_modules/.bin/jest
 PASS  source/platforms/github/_tests/_github_git.test.ts
 PASS  source/runner/_tests/_executor.test.ts
  ● Console

    console.error source/runner/Executor.ts:291
      Danger has errored
    console.error source/runner/Executor.ts:292
      { Error: ENOENT: no such file or directory, open ''
          at Object.fs.openSync (fs.js:646:18)
          at Object.fs.readFileSync (fs.js:551:33)
          at Object.<anonymous> (/Users/gregor/Projects/octokit/rest-test-repos/danger-js2/source/runner/runners/inline.ts:88:63)
          at step (/Users/gregor/Projects/octokit/rest-test-repos/danger-js2/source/runner/runners/inline.ts:32:23)
          at Object.next (/Users/gregor/Projects/octokit/rest-test-repos/danger-js2/source/runner/runners/inline.ts:13:51)
          at /Users/gregor/Projects/octokit/rest-test-repos/danger-js2/source/runner/runners/inline.ts:7:71
          at new Promise (<anonymous>)
          at Object.<anonymous>.__awaiter (/Users/gregor/Projects/octokit/rest-test-repos/danger-js2/source/runner/runners/inline.ts:3:12)
          at Object.runDangerfileEnvironment (/Users/gregor/Projects/octokit/rest-test-repos/danger-js2/source/runner/runners/inline.ts:69:12)
          at Executor.<anonymous> (/Users/gregor/Projects/octokit/rest-test-repos/danger-js2/source/runner/Executor.ts:112:58) errno: -2, code: 'ENOENT', syscall: 'open', path: '' }
    console.log source/runner/Executor.ts:257
      Failing the build, there is 1 fail.
    console.log source/runner/Executor.ts:248
      No issues or messages were sent. Removing any existing messages.
    console.log source/runner/Executor.ts:264
      Found only warnings, not failing the build.
    console.log source/runner/Executor.ts:264
      Found only warnings, not failing the build.
    console.log source/runner/Executor.ts:264
      Found only warnings, not failing the build.
    console.log source/runner/Executor.ts:257
      Failing the build, there is 1 fail.
    console.log source/runner/Executor.ts:257
      Failing the build, there is 1 fail.

 PASS  source/platforms/_tests/_github.test.ts
 PASS  source/platforms/github/_tests/_github_api.test.ts
 PASS  source/ci_source/providers/_tests/_circle.test.ts
 PASS  source/ci_source/providers/_tests/_vsts.test.ts
 PASS  source/ci_source/providers/_tests/_semaphore.test.ts
 PASS  source/api/_tests/fetch.test.ts
  ● Console

    console.warn source/api/fetch.ts:92
      Request failed [500]: http://localhost:30001/
    console.warn source/api/fetch.ts:102
      Response: {
        "key": "valid json"
      }
    console.warn source/api/fetch.ts:92
      Request failed [500]: http://localhost:30001/
    console.warn source/api/fetch.ts:106
      Response: any plain text response

 PASS  source/runner/templates/_tests/_githubIssueTemplates.test.ts
 PASS  source/ci_source/providers/_tests/_travis.test.ts
 PASS  source/ci_source/providers/_tests/_dockerCloud.test.ts
 PASS  source/ci_source/providers/_tests/_buddyBuild.test.ts
 PASS  source/ci_source/providers/_tests/_buildkite.test.ts
 PASS  source/runner/_tests/json-to-context.test.ts
 PASS  source/ci_source/providers/_tests/_bitrise.test.ts
 PASS  source/commands/utils/_tests/dangerRunToRunnerCLI.test.ts
 PASS  source/ci_source/providers/_tests/_jenkins.test.ts
 PASS  source/ci_source/providers/_tests/_drone.test.ts
 PASS  source/platforms/github/_tests/_github_utils.test.ts
 PASS  source/ci_source/providers/_tests/_nevercode.test.ts
 PASS  source/runner/_tests/_danger_utils.test.ts
 PASS  source/runner/_tests/jsonToDSL.test.ts
 PASS  source/runner/runners/_tests/_cleanDangerfile.test.ts
 PASS  source/runner/runners/_tests/vm2.test.ts (11.635s)
  ● Console

    console.error source/runner/runners/vm2.ts:113
      Unable to evaluate the Dangerfile
    console.error source/runner/runners/vm2.ts:113
      Unable to evaluate the Dangerfile
    console.error source/runner/runners/vm2.ts:113
      Unable to evaluate the Dangerfile

 PASS  source/commands/utils/_tests/file-utils.test.ts
 PASS  source/ci_source/_tests/_get_ci_source.test.ts
  ● Console

    console.error source/ci_source/get_ci_source.ts:68
      could not load CI provider at ./dummy_ci.js due to Error: ENOENT: no such file or directory, stat '/Users/gregor/Projects/octokit/rest-test-repos/danger-js2/dummy_ci.js'

 PASS  source/platforms/git/_tests/localGetCommits.test.ts
 PASS  source/platforms/github/_tests/_pull_request_parser.test.ts
 PASS  source/platforms/_tests/_platform.test.ts
  ● Console

    console.error source/platforms/platform.ts:14
      The DANGER_GITHUB_API_TOKEN environmental variable is missing
    console.error source/platforms/platform.ts:15
      Without an api token, danger will be unable to comment on a PR

 PASS  source/runner/runners/utils/_tests/_transpiler.test.ts

Test Suites: 30 passed, 30 total
Tests:       242 passed, 242 total
Snapshots:   6 passed, 6 total
Time:        14.137s
Ran all test suites.
✨  Done in 15.43s.
```
</details>

**Comment by orta** [comment]
Thanks, I bet there's some of my `process.env` leaking into the expectation :-/
