### ISSUE TITLE
Babel 7 issue

### ISSUE THREAD

**Issue by azz** [danger/danger-js#562]
I've upgraded a project to babel 7 (`beta.44`) and I get this error:

```
[10:34:42]	$ /node_modules/.bin/danger ci
[10:34:52]	Error:  ReferenceError: Using removed Babel 6 option: .sourceMapTarget - The `sourceMapTarget` option has been removed because it makes more sense for the tooling that calls Babel to assign `map.file` themselves.
[10:34:52]	    at buildUnknownError (/node_modules/@babel/core/lib/config/validation/options.js:97:11)
[10:34:52]	    at /node_modules/@babel/core/lib/config/validation/options.js:86:57
[10:34:52]	    at Array.forEach (<anonymous>)
[10:34:52]	    at validate (/node_modules/@babel/core/lib/config/validation/options.js:64:21)
[10:34:52]	    at loadPrivatePartialConfig (/node_modules/@babel/core/lib/config/partial.js:38:48)
[10:34:52]	    at loadFullConfig (/node_modules/@babel/core/lib/config/full.js:43:37)
[10:34:52]	    at transformSync (/node_modules/@babel/core/lib/transform-sync.js:15:36)
[10:34:52]	    at Object.transform (/node_modules/@babel/core/lib/transform.js:22:65)
[10:34:52]	    at Object.exports.babelify (/node_modules/danger/distribution/runner/runners/utils/transpiler.js:85:24)
[10:34:52]	    at Object.exports.default (/node_modules/danger/distribution/runner/runners/utils/transpiler.js:105:26)
```

Relevant dependencies:

```json
    "@babel/core": "7.0.0-beta.44",
    "@babel/plugin-proposal-class-properties": "7.0.0-beta.44",
    "@babel/plugin-proposal-object-rest-spread": "7.0.0-beta.44",
    "@babel/plugin-transform-destructuring": "7.0.0-beta.44",
    "@babel/preset-env": "7.0.0-beta.44",
    "@babel/preset-react": "7.0.0-beta.44",
    "@babel/preset-typescript": "7.0.0-beta.44",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^22.4.3",
    "babel-loader": "^8.0.0-beta.0",
    "danger": "^3.4.5",
```

**Comment by azz** [comment]
_sigh_

https://github.com/danger/danger-js/commit/8265595648a907b648d22b2b0605778b57d7cb4d

**Comment by orta** [comment]
:D
