### ISSUE TITLE
danger fails to run locally when diff is larger than maxBuffer size

### ISSUE THREAD

**Issue by samdmarshall** [danger/danger-js#571]
When running danger locally, it runs the command `git diff master...HEAD` to generate a diff to work on. This command is executed using the default `maxBuffer` [here](https://github.com/danger/danger-js/blob/master/source/platforms/git/localGetDiff.ts#L11).

Backtrace: 
```
(demi) yarn danger local --verbose
yarn run v1.6.0
$ /home/demi/pewpewthespells-com/node_modules/.bin/danger local --verbose
Could not get diff from git between master and HEAD
{ Error: stdout maxBuffer exceeded
    at Socket.onChildStdout (child_process.js:305:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:250:12)
    at readableAddChunk (_stream_readable.js:233:13)
    at Socket.Readable.push (_stream_readable.js:195:10)
    at Pipe.onread (net.js:586:20) cmd: 'git diff master...HEAD' }
Done in 1.53s.
```
The problem originates from the [default being 200kb](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback), and large git diffs can easily exceed that (in my case the diff was 24mb). I was able to get past this issue by locally modifying my danger module code to include a much larger maxBuffer size, but beyond putting a ridiculously large constant in the code, i'm not sure what the best patch for this problem is.

**Comment by orta** [comment]
I guess it can also read/write to a temp file? But TBH maybe a higher buffer is fine, might take a bit of time

**Comment by orta** [comment]
Could it be sending binary files through too? Maybe there's a flag for that

**Comment by samdmarshall** [comment]
after modifying it locally; it looks like doing a simple pipe modification to the existing `git diff master...HEAD` command to send output to a temp file would work fine; though I don't know about the compatibility that has with various shells or how node-js handles that kind of exec (if it is in its own `bash -c "..."` or not).

**Comment by DaveRubin** [comment]
I also encountered this problem.
though increasing the buffer size worked for me 
(line 10 in localGetDiff.js)
`child_process_1.exec(call,{maxBuffer: 1024 * 2000}, function (err, stdout, _stderr) {`
wouldn't it be better to use spawn instead of exec for this task?
https://www.hacksparrow.com/difference-between-spawn-and-exec-of-node-js-child_process.html

**Comment by orta** [comment]
Ah, yeah - this sounds good, I don't recall having any reason for using spawn, likely just had some previous code that uses it and re-used that

**Comment by DaveRubin** [comment]
Nice, if you'll want, i could try and create a pr for this issue later on this week.

would be nice to contribute 😄

**Comment by sunshinejr** [comment]
Oh, `spawn` looks awesome! TIL. Pretty sure you can go ahead and make a PR @DaveRubin. Then @samdmarshall could test it if it works for her as well.

**Comment by joshacheson** [comment]
It looks like this was left behind - I'm happy to do whatever work here is needed. With that said, for me to do so (or more accurately for any change to help me with the problem I'm experience), I need to not just migrate from `exec` to `spawn`, but also need:

1) A much higher default maxBuffer, or
2) the ability to pass a custom maxBuffer some way or another

Which of these s most agreeable? Or... is it neither?

**Comment by orta** [comment]
I'm happy with any of the options, because I don't know enough of the tradeoffs to make a very strong opinion - all both (exec + maxBuffer and spawn) all seem pretty reasonable to me the temp file one is a bit off because I want it to still feel like it works how Peril works (which is STDIN via JSON)

**Comment by samdmarshall** [comment]
as an end-user this is not a problem I expect to have, but I also have reservations about picking some other arbitrary high-value constant. That seems to be why the existing default is 200kb. For people working in either large code-bases or with a lot of formatted text, this seems like a potential hazard. For the record, this issue arose because i was looking at migrating a repo of my website content over to using danger-js and/or peril to do a bunch of validation and linting before I did any deployments. So the resulting 24mb diff i mention is purely just textual content I host on my site. while this one particular diff might be an extreme case, i don't think it would be uncommon for people working with commiting pods or other dependencies into their working repo as well as working with generated code.

**Comment by orta** [comment]
Part of me wonders if the diff shouldn't be sent across the STDIN/OUT at all, and instead is created inside the sub-process. It just doesn't scale well. 

It's a bit of a chore for external runners like danger-swift, but I'm not sure how often people are really interested in looking at the diff itself instead of being interested in files changed, and general numbers.

**Comment by joshacheson** [comment]
I think my strategy will be to make `maxBuffer` configurable. I'm not sure of another solution that makes a lot of sense.

FWIW in my project I'm actually just accessing the private `LocalGit` class directly, and so I would be happy to just add configuration from that path downwards. I can also

1) Add a cli arg for this
2) Make this globally configurable at runtime one way or another (if there is some global I can tap in to, which maybe there's not... haven't really looked yet).

@orta I use the diff itself, fwiw

**Comment by samdmarshall** [comment]
@joshacheson perhaps i'm misunderstanding what you are proposing here, but it sounds like you are suggesting that the existing default of 200kb be left as-is and introduce a new flag or configuration open that will allow the end-user to configure what they want the upper limit of the buffer size to be by default?

If that is the case, then wouldn't the end-user still have to dig into finding out why:

1. why danger is faili

1. why danger is failing


2. understand the buffer limit for passing data between sub-processes

3. associate that with the new flag or config value to increase the buffer size

4. work out the exact command danger-js is using to figure out how to get the size of their diff is

5. input that value where appropriate

**Comment by joshacheson** [comment]
Those are great points!

So first, yes, you're understanding my suggestion correctly. But I'm glad you pointed out the pitfalls of my suggestion. Here are the thoughts I'm working with:

1) The default seems to work for most people (or else there'd be more chatter / more issues about it, I assume)
2) What _I_ want the new value to be might be too much / unnecessarily large for many others
3) I'm not really comfortable making decisions about `exec` vs. `spawn`, and I don't know if migrating to `spawn` solves my problem, and moreover whether it does so without breaking changes for others
4) `maxBuffer` does definitely solve my problem, and by keeping the current value as a default but making it configurable, I can feel good about satisfying my own use case whilst not causing breaking changes for others

With all of this, I would absolutely want to address your concerns about the developer experience. If it's possible (and I'm happy to look in to it), how would you feel about "helpful error messaging" as the solution to this problem? We could, if encountering the error that has lead us to this issue, simply log to the console that there is an available `maxBuffer` configuration, and perhaps also link to the documentation for this configuration. In the past I've found error messaging like this helpful enough (being guided to a way to solve a problem has always seemed like good enough for me).

Anyways, curious to know your thoughts. I do want to choose a solution that works well for everyone.

**Comment by orta** [comment]
It's likely just there because spawn has a better consumer API, we use exec in what I consider the critical path of Danger JS ( e.g. running `danger ci` ) so I think it makes sense to just use it everywhere

**Comment by samdmarshall** [comment]
to be perfectly honest if this is something I will have to configure per repo or per invocation of danger-js then I might as well switch back to the ruby version or investigate other options. this is why i'm leaning towards whichever solution removes needing to think about this to get work done as an individual contributor on a team.

**Comment by joshacheson** [comment]
Yeah, I understand. It might be acceptable just to... drastically increase the default. But to be honest, I have _no idea_ how this might affect current users (which I'm really concerned about).

Making this configurable and bumping the default might be the best option. This way, most people wouldn't have to think about it, and those who need a specifically lower `maxBuffer` (for whatever reason that I can't imagine right now) can customize it to be lower.

Is this amenable for you? @orta do you have a preference?

**Comment by orta** [comment]
Yep, switch to `exec` which doesn't have this problem and is consistent with `danger ci`

**Comment by joshacheson** [comment]
Sorry, I might be confused, but I think `exec` is [what's currently used](https://github.com/danger/danger-js/blob/master/source/platforms/git/localGetDiff.ts#L11-L19)

**Comment by orta** [comment]
Ah yeah the one 👍  sorry

**Comment by samdmarshall** [comment]
alternative solution: what about using `git format-patch`? it seems that you can invoke `git format-patch --no-binary <base>...<head>` and it will write out each commit as a separate `.patch` file. you can additionally specify an output directory to dump these patch files into (rather than the current), and that seems like it would be giving a lot more visibility into the PR than just a whole-sale diff of the change-set?

maybe the smart thing is to just swap to `spawn` instead of `exec` and then make this a future feature or something.
