### ISSUE TITLE
Peril Error: `TypeError: previousComments.filter is not a function`

### ISSUE THREAD

**Issue by milesalex** [danger/danger-js#577]
This error is happening in peril against this dangerfile: https://github.com/TokenTax/peril/blob/master/dangerfiles/issues.ts

The error is potentially coming from this line
https://github.com/danger/danger-js/blob/67ed2ba5e7dedf52f502393f50bfc21901ff8943/source/runner/Executor.ts#L298

```
2018-04-27T13:28:33.040322+00:00 app[web.1]: Unable to evaluate the Dangerfile
2018-04-27T13:28:33.043195+00:00 app[web.1]: info: [runner] - Commenting, with results:
2018-04-27T13:28:33.043198+00:00 app[web.1]: mds: 1
2018-04-27T13:28:33.043200+00:00 app[web.1]: messages: 0
2018-04-27T13:28:33.043201+00:00 app[web.1]: warns: 0
2018-04-27T13:28:33.043203+00:00 app[web.1]: fails: 1
2018-04-27T13:28:33.043205+00:00 app[web.1]:
2018-04-27T13:28:33.049339+00:00 app[web.1]: Failing the build, there is 1 fail.
2018-04-27T13:28:33.058095+00:00 app[web.1]: error: Error:  TypeError: previousComments.filter is not a function
2018-04-27T13:28:33.058099+00:00 app[web.1]:     at Executor.sendInlineComments (/app/node_modules/danger/distribution/runner/Executor.js:365:47)
2018-04-27T13:28:33.058101+00:00 app[web.1]:     at Executor.<anonymous> (/app/node_modules/danger/distribution/runner/Executor.js:305:51)
2018-04-27T13:28:33.058103+00:00 app[web.1]:     at step (/app/node_modules/danger/distribution/runner/Executor.js:32:23)
2018-04-27T13:28:33.058104+00:00 app[web.1]:     at Object.next (/app/node_modules/danger/distribution/runner/Executor.js:13:53)
2018-04-27T13:28:33.058106+00:00 app[web.1]:     at fulfilled (/app/node_modules/danger/distribution/runner/Executor.js:4:58)
2018-04-27T13:28:33.058108+00:00 app[web.1]:     at <anonymous>
2018-04-27T13:28:33.058110+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:182:7)
2018-04-27T13:28:33.058556+00:00 app[web.1]: /app/out/peril.js:24
2018-04-27T13:28:33.058559+00:00 app[web.1]:         throw reason;```

**Comment by mxstbr** [comment]
That did not fix the bug, reopening.

**Comment by mxstbr** [comment]
So apparently, `previousComments` isn't false-y, it's just not an array. Why could that happen, what else could it be?!
