### ISSUE TITLE
previousComments.filter is not a function

### ISSUE THREAD

**Issue by mxstbr** [danger/danger-js#584]
This happens for us on any run that targets a new issue just being opened: (for example https://github.com/withspectrum/spectrum/issues/2994)

```
2018-05-02T14:09:36.626079+00:00 app[web.1]: info: ## issues.edited on unknown
2018-05-02T14:09:36.626216+00:00 app[web.1]: info:    1 runs needed: dangerfile.issues.ts
2018-05-02T14:09:38.029297+00:00 heroku[router]: at=info method=POST path="/webhook" host=peril-spectrum.herokuapp.com request_id=1dcc82ff-cf35-4f51-bcb3-e1554f08ee4c fwd="192.30.252.36" dyno=web.1 connect=3ms service=1443ms status=200 bytes=1886 protocol=https
2018-05-02T14:09:38.014458+00:00 app[web.1]: Unable to evaluate the Dangerfile
2018-05-02T14:09:38.019091+00:00 app[web.1]: info: [runner] - Commenting, with results: 
2018-05-02T14:09:38.019095+00:00 app[web.1]: mds: 1
2018-05-02T14:09:38.019096+00:00 app[web.1]: messages: 0
2018-05-02T14:09:38.019098+00:00 app[web.1]: warns: 0
2018-05-02T14:09:38.019100+00:00 app[web.1]: fails: 1
2018-05-02T14:09:38.019102+00:00 app[web.1]:   
2018-05-02T14:09:38.022778+00:00 app[web.1]: Failing the build, there is 1 fail.
2018-05-02T14:09:38.034880+00:00 app[web.1]: error: Error:  TypeError: previousComments.filter is not a function
2018-05-02T14:09:38.034890+00:00 app[web.1]:     at Executor.sendInlineComments (/app/node_modules/danger/distribution/runner/Executor.js:365:47)
2018-05-02T14:09:38.034893+00:00 app[web.1]:     at Executor.<anonymous> (/app/node_modules/danger/distribution/runner/Executor.js:305:51)
2018-05-02T14:09:38.034894+00:00 app[web.1]:     at step (/app/node_modules/danger/distribution/runner/Executor.js:32:23)
2018-05-02T14:09:38.034896+00:00 app[web.1]:     at Object.next (/app/node_modules/danger/distribution/runner/Executor.js:13:53)
2018-05-02T14:09:38.034897+00:00 app[web.1]:     at fulfilled (/app/node_modules/danger/distribution/runner/Executor.js:4:58)
2018-05-02T14:09:38.034899+00:00 app[web.1]:     at <anonymous>
2018-05-02T14:09:38.034901+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:182:7)
2018-05-02T14:09:38.035229+00:00 app[web.1]: /app/out/peril.js:24
2018-05-02T14:09:38.035232+00:00 app[web.1]:         throw reason;
2018-05-02T14:09:38.035233+00:00 app[web.1]:         ^
2018-05-02T14:09:38.035235+00:00 app[web.1]: 
2018-05-02T14:09:38.035239+00:00 app[web.1]: TypeError: previousComments.filter is not a function
2018-05-02T14:09:38.035241+00:00 app[web.1]:     at Executor.sendInlineComments (/app/node_modules/danger/distribution/runner/Executor.js:365:47)
2018-05-02T14:09:38.035242+00:00 app[web.1]:     at Executor.<anonymous> (/app/node_modules/danger/distribution/runner/Executor.js:305:51)
2018-05-02T14:09:38.035259+00:00 app[web.1]:     at step (/app/node_modules/danger/distribution/runner/Executor.js:32:23)
2018-05-02T14:09:38.035261+00:00 app[web.1]:     at Object.next (/app/node_modules/danger/distribution/runner/Executor.js:13:53)
2018-05-02T14:09:38.035262+00:00 app[web.1]:     at fulfilled (/app/node_modules/danger/distribution/runner/Executor.js:4:58)
2018-05-02T14:09:38.035264+00:00 app[web.1]:     at <anonymous>
2018-05-02T14:09:38.035266+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:182:7)
```

Here's our Dangerfile: https://github.com/withspectrum/peril-settings/blob/master/dangerfile.issues.ts It was working perfectly fine until I pushed the latest update, so I think this is a regression?

**Comment by sunshinejr** [comment]
Yeah, this is similar to #577 I guess. Probably a regression from the inline mode, as we tested it mostly using Danger itself. Was this the first issue after the update?

**Comment by mxstbr** [comment]
Oh yeah that's totally a duplicate, sorry my bad! Will close this in favour of #577
