### ISSUE TITLE
V8 Assertion error under node 10

### ISSUE THREAD

**Issue by azz** [danger/danger-js#587]
I got this interesting error when switching from a docker `node:9` image to [`cypress/base:10`](https://hub.docker.com/r/cypress/browsers/~/dockerfile/) (which has node 10).

```
/usr/local/bin/node[1842]: ../src/node_contextify.cc:631:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.

 1: 
node::Abort() [/usr/local/bin/node]
 2: 
0x87b6c5 [/usr/local/bin/node]
 3: 
node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: 
v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: 
0xad5b9f [/usr/local/bin/node]
 6: 
v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x26dee4e8427d
Error:  Error: Results passed to Danger JS did not include fails.

{}
    at /home/e40ccd31d1a3d9d9/node_modules/danger/distribution/dsl/DangerResults.js:20:19
    at Array.forEach (<anonymous>)
    at Object.validateResults (/home/e40ccd31d1a3d9d9/node_modules/danger/distribution/dsl/DangerResults.js:16:24)
    at Executor.<anonymous> (/home/e40ccd31d1a3d9d9/node_modules/danger/distribution/runner/Executor.js:161:41)
    at step (/home/e40ccd31d1a3d9d9/node_modules/danger/distribution/runner/Executor.js:32:23)
    at Object.next (/home/e40ccd31d1a3d9d9/node_modules/danger/distribution/runner/Executor.js:13:53)
    at /home/e40ccd31d1a3d9d9/node_modules/danger/distribution/runner/Executor.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/e40ccd31d1a3d9d9/node_modules/danger/distribution/runner/Executor.js:3:12)
    at Executor.handleResults (/home/e40ccd31d1a3d9d9/node_modules/danger/distribution/runner/Executor.js:157:16)

```

Not sure if it is actionable as it is probably difficult to reproduce, but I thought I'd raise it nonetheless.

**Comment by orta** [comment]
I habe node 10 on CI now 👍

**Comment by orta** [comment]
Adding it does? the danger-js codebase doesn't have `natives` as a dependency (happy to add it?)

**Comment by azz** [comment]
I'm not really sure 😢 adding it to our root package didn't make a difference, when we added it to `danger` we got a different error.

I ran this in a fresh directory:

```sh
npm init -y
npm i danger
ag 'process.binding('
```

and didn't find anything requiring `contextify` so I'm not really sure what's causing this.

**Comment by orta** [comment]
:-/ - I dunno man
