### ISSUE TITLE
Cannot find module 'jest-runtime'

### ISSUE THREAD

**Issue by DanielRosenwasser** [danger/danger-js#62]
I tried playing around with Danger, but I immediately hit a wall when trying to run it. Running on Windows, but I'm not sure if that has anything to do with it.

From my `package.json`:
```json
  "scripts": {
    "danger": "danger"
  },
  "devDependencies": {
    "danger": "^0.7.0"
  }
```

```
> npm run danger

> foo@1.0.0 danger C:\foo
> danger

module.js:472
    throw err;
    ^

Error: Cannot find module 'jest-runtime'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\foo\node_modules\danger\distribution\runner\DangerfileRunner.js:80:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by orta** [comment]
Ah yeah, looks like this isn't [added to the package.json](https://github.com/danger/danger-js/blob/23f2995c211bf432b6124ddb32d6180d4737d5a5/package.json#L61)

**Comment by orta** [comment]
fixed by https://github.com/danger/danger-js/pull/63

**Comment by orta** [comment]
Just shipped 0.7.1 - wanna see if that fixes it?

**Comment by dblock** [comment]
Newer issue, #83

**Comment by macklinu** [comment]
I haven't experienced this issue using danger>=0.7.1. I'm going to close this in favor of #84. Please reopen if you're still experiencing an issue, @DanielRosenwasser. 👍
