### ISSUE TITLE
danger.github.utils.fileContents fails on

### ISSUE THREAD

**Issue by ChristianHj** [danger/danger-js#780]
* danger.github.utils.fileContents worked fine in version 3.x.
* Upgraded to version 6.1.8 and got the error below.
* Had to downgrade to 4.4.10 where it seems to work again, but with a octokit deprecation warning.

Has there been any breaking changes to this function between version 4 and 6? 🙂 

The following line fails:
`let fileContentsPromise = danger.github.utils.fileContents('somefile.txt');`

With the following error:
```
Cannot read property 'filename' of undefined
TypeError: Cannot read property 'filename' of undefined
    at exports.shouldUseGitHubOverride (C:\GIT\*******\node_modules\danger\distribution\platforms\github\customGitHubRequir

e.js:120:16)
    at Function._module2.default._load (C:\GIT\*******\node_modules\override-require\dist\overrideRequire.js:38:9)
    at Object.<anonymous> (dangerfile.ts:5:29)
    at Module._compile (module.js:652:30)
    at Object.requireFromString [as default] (C:\GIT\*******\node_modules\require-from-string\index.js:28:4)
    at Object.<anonymous> (C:\GIT\*******\node_modules\danger\distribution\runner\runners\inline.js:144:63)
`
    at step (C:\GIT\*******\node_modules\danger\distribution\runner\runners\inline.js:32:23)
    at Object.next (C:\GIT\*******\node_modules\danger\distribution\runner\runners\inline.js:13:53)
    at C:\GIT\*******\node_modules\danger\distribution\runner\runners\inline.js:7:71
    at new Promise (<anonymous>)
```

**Comment by orta** [comment]
I don't think so, no, and I use this a lot in everyday work - maybe the GitHub API shape changed?
