### ISSUE TITLE
Incorrect Code-Generation when import happens across multiple lines

### ISSUE THREAD

**Issue by fbartho** [danger/danger-js#829]
I entered the following line at the top of my otherwise working danger file:
```typescript
import { danger, fail, markdown, schedule, warn, message, results } from "danger";
```
This added `results` to the list of things I was importing.
Prettier reformatted that to the following:
```typescript
import {
	danger,
	fail,
	markdown,
	schedule,
	warn,
	message,
	results,
} from "danger";
```
This then threw the following error:
```$ /github/workspace/node_modules/.bin/danger ci
Unable to evaluate the Dangerfile
 TypeError: Cannot read property 'github' of 
    at Object.<anonymous> (dangerfile.ts:39:26)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.requireFromString [as default] (/github/workspace/node_modules/require-from-string/index.js:28:4)
    at Object.<anonymous> (/github/workspace/node_modules/danger/distribution/runner/runners/inline.js:144:63)
    at step (/github/workspace/node_modules/danger/distribution/runner/runners/inline.js:32:23)
    at Object.next (/github/workspace/node_modules/danger/distribution/runner/runners/inline.js:13:53)
    at /github/workspace/node_modules/danger/distribution/runner/runners/inline.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/github/workspace/node_modules/danger/distribution/runner/runners/inline.js:3:12)
    at exports.runDangerfileEnvironment (/github/workspace/node_modules/danger/distribution/runner/runners/inline.js:105:136)
```
The GitHub comment posted by danger tried to highlight a blank line as erroneous. I assume that it's just off by a few lines due to the code-generation process.

Workaround, when used `// prettier-ignore` to keep it on one line the problem went away!

**Comment by fbartho** [comment]
It looks like this is the problematic line / regex:
https://github.com/danger/danger-js/blob/174f8e18bc794af8d2d54f518ae347d95cefd335/source/runner/runners/utils/cleanDangerfile.ts#L4
