### ISSUE TITLE
Cannot start danger with checks API setup

### ISSUE THREAD

**Issue by ggajews** [danger/danger-js#842]
It looks like danger is not correctly set to run with Github Checks API only.
I'm starting danger with command
`yarn danger ci --use-github-checks --text-only`
This is the stacktrace I'm getting:
```
The DANGER_GITHUB_API_TOKEN/DANGER_BITBUCKETSERVER_HOST environmental variable is missing
Without an api token, danger will be unable to comment on a PR
Error:  Error: Cannot use authenticated API requests.
    at Object.getPlatformForEnv (/home/circleci/project/node_modules/danger/distribution/platforms/platform.js:51:11)
    at Object.<anonymous> (/home/circleci/project/node_modules/danger/distribution/commands/ci/runner.js:81:57)
    at step (/home/circleci/project/node_modules/danger/distribution/commands/ci/runner.js:32:23)
    at Object.next (/home/circleci/project/node_modules/danger/distribution/commands/ci/runner.js:13:53)
    at fulfilled (/home/circleci/project/node_modules/danger/distribution/commands/ci/runner.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
error Command failed with exit code 1.
```

I have only `DANGER_JS_APP_INSTALL_ID ` set in envirovment.

**Comment by hawkrives** [comment]
Don't you still need an authorization token in order to use the checks API?

**Comment by ggajews** [comment]
According to Changelog nope.
>This brings some interesting architectural changes inside Danger, but more important to you dear reader, is that using the Checks API has some API restrictions. This makes in infeasible to re-use the user access token which we've previously been recommending for setup.

> Instead there are two options:
> Use a GitHub app owned by Danger: https://github.com/apps/danger-js
> Use your own GitHub app.
> The security model of the GitHub app means it's totally safe to use our GitHub app, it can only read/write to checks and has no access to code or organizational data. It's arguably safer than the previous issue-based comment.
>To use it, you need to hit the above link, install the app on the org of your choice and then get the install ID from the URL you're redirected to. Set that in your CI's ENV to be DANGER_JS_APP_INSTALL_ID and you're good to go.

**Comment by milesj** [comment]
Just ran into the same problem... Any solution?

**Comment by milesj** [comment]
Using the danger-js app + the required token results in 2 status checks. This is super annoying.

<img width="695" alt="Screen Shot 2019-04-18 at 11 18 05 AM" src="https://user-images.githubusercontent.com/143744/56382539-7b37fc00-61cc-11e9-91f5-2715916c6542.png">

**Comment by orta** [comment]
You're welcome to take a look, we mostly use Danger via Peril (or in OSS repos using the access token) so I don't really get this happening personally and I don't have enough the time to fix bug for other folk and maintain this much oss
