### ISSUE TITLE
Generated bin for Brew doesn't work

### ISSUE THREAD

**Issue by f-meloni** [danger/danger-js#958]
If you run `yarn package` and then you try to execute the generated bin (I think this is possible only on Mac, can not be executed on other platforms) `brew-distribution/danger` with any command
e.g.
```
brew-distribution/danger pr https://github.com/danger/danger-js/pull/956
```

You will get this error

```
internal/modules/cjs/loader.js:594
    throw err;
    ^

Error: Cannot find module 'runner'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:592:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1278:46)
    at Function.Module._load (internal/modules/cjs/loader.js:518:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:832:14)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket._destroy (net.js:602:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:834:10)
```

**Comment by HelloCore** [comment]
I created this PR https://github.com/danger/danger-js/pull/970 to fix this, and it works on my device, but I'm not sure about other use cases.

I tried the binary version `9.1.5` from homebrew, and it doesn't work on my device.
I wonder if there's the underlying issue here 🤔
