### ISSUE TITLE
Gitlab rRest api doesn't accept Project name anymore

### ISSUE THREAD

**Issue by farabi** [danger/danger-js#969]
Hello.

Danger is trying to call the Gitlab rest api using the project name. while gitlab now only accepts the project ID as you can see in the documentation.

Here is the error, i get.

+ danger-swift ci
Error:  { HTTPError: Not Found
    at fn (/snapshot/danger-js/node_modules/ky/umd.js:242:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HTTPError',
  response:
   Response {
     size: 0,
     timeout: 0,
     [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
     [Symbol(Response internals)]:
      { url:
         'https://gitlab.xxxx.com/api/v4/projects/project%2Fname/merge_requests/15/changes',
        status: 404,
        statusText: 'Not Found',
        headers: [Headers] } },
  description: '404 Project Not Found' }

**Comment by chebur** [comment]
same

**Comment by orta** [comment]
Cool, makes sense - someone want to take a look at a fix?

**Comment by farabi** [comment]
@orta 
I will !

**Comment by farabi** [comment]
@orta  
Dumb question, but how to compile a danger-js to use it as a danger-swift dependency ?

**Comment by HelloCore** [comment]
> @orta
> Dumb question, but how to compile a danger-js to use it as a danger-swift dependency ?

I believe it's this command `yarn run build; yarn run pkg . --output brew-distribution/danger;`.
Copied from https://github.com/danger/danger-js/blob/dab0e63a97705617c0e0017d85a9ff7129cadd5f/package.json#L69

**Comment by f-meloni** [comment]
that could not work given https://github.com/danger/danger-js/issues/958 :(

**Comment by HelloCore** [comment]
@farabi The pr https://github.com/danger/danger-js/pull/970 got merged to master, you could use `yarn run build; yarn run pkg . --output brew-distribution/danger;` to build the binary. Also, don’t forget to run `yarn install`

**Comment by farabi** [comment]
Hello @orta  @chebur 

Actually gitlab does accept project name, the issue is coming from apache configuration where local gitlab is hosted.
Unless AllowEncodedSlashes is set to on.  rest calls with encoded slashes will not work. 
Like in my case : "https://gitlab.xxxx.com/api/v4/projects/project%2Fname/merge_requests/15/changes"

**The solution i did in my fork** is to add a env variable "DANGER_GITLAB_PROJECT_ID". and if it's not defined then we use the project name.

Lot of tools are using the same approach with the project id.

If its ok for you, i add a pull request about that. otherwise , we close the ticket and i will keep using my fork. farabi/tap/danger-swift

**Comment by orta** [comment]
Seems like a good PR to me 👍

**Comment by lazy-var** [comment]
In addition to @farabi apache configuration suggestion, I needed **NoDecode** and **nocanon** parameters:

```
<VirtualHost *:port>
  AllowEncodedSlashes NoDecode

  <Location /example/>
    ProxyPass http://anotherserver:8080/example nocanon
  </Location>
</VirtualHost>
```
as explained here: https://stackoverflow.com/a/9933890

**Comment by AnthonyMastrean** [comment]
I just got started with danger-js 10.0 and am seeing results like this.

```
> danger pr https://gitlab.com/vaeit/danger-examples/-/merge_requests/1

Starting Danger PR on vaeit/danger-examples/-#1
Error:  HTTPError: Not Found
    at fn (C:\Users\anthony\Work\gitlab.com\vaeit\danger-examples\node_modules\ky\umd.js:266:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Ky._retry (C:\Users\anthony\Work\gitlab.com\vaeit\danger-examples\node_modules\ky\umd.js:334:12) {
  name: 'HTTPError',
  response: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://gitlab.com/api/v4/projects/vaeit%2Fdanger-examples%2F-/merge_requests/1/changes',
      status: 404,
      statusText: 'Not Found',
      headers: [Headers],
      counter: 0
    }
  },
  description: '404 Project Not Found'
}
```

Besides this API change from project name to project ID, this URL looks weird anyway... was the "/-/" from the browser address carried into the repo slug? I don't think it's supposed to be part of the API URL.

```
https://gitlab.com/api/v4/projects/vaeit%2Fdanger-examples%2F-/merge_requests/1/changes
                                                          ^---^
```

**Comment by ivankatliarchuk** [comment]
The intention is right to support project number ID, but Gitlab does support `The ID or [URL-encoded path of the project](https://docs.gitlab.com/ee/api/index.html#namespaced-path-encoding).` so both are working.
